var tagValues = [
  ["APZa1", "religious contributions"],
  ["APZa2", "libation formula"],
  ["ARZf1", "libation formula"],
  ["ARZf2", "libation formula"],
  ["CR(?)Zf1", "religious objects"],
  ["HT102", "wrong total"],
  ["HT94a", "wrong total"],
  ["HT117", "longest text"],
  ["HT118", "wrong total"],
  ["HT119", "wrong total"],
  ["HT11a", "wrong total"],
  ["HT13", "wrong total"],
  ["HT93a", "longest text"],
  ["HT93b", "longest text"],
  ["HT9a", "wrong total"],
  ["IOZa11", "written right to left"],
  ["IOZa2", "libation formula"],
  ["IOZa3", "libation formula"],
  ["IOZa4", "libation formula"],
  ["IOZa5", "religious objects"],
  ["IOZa6", "libation formula"],
  ["IOZa7", "libation formula"],
  ["IOZa8", "libation formula"],
  ["IOZa9", "libation formula"],
  ["IOZa9", "written right to left"],
  ["IOZb10", "libation formula"],
  ["KAZf1", "religious objects"],
  ["KNZa10", "libation formula"],
  ["KNZa17", "religious objects"],
  ["KNZa18", "religious objects"],
  ["KNZa19", "religious objects"],
  ["KNZa19", "written right to left"],
  ["KNZc6", "religious objects"],
  ["KNZc7", "libation formula"],
  ["KNZe44", "libation formula"],
  ["KNZf13", "religious objects"],
  ["KNZf31", "religious objects"],
  ["KO(?)Zf2", "religious objects"],
  ["KOZa1", "libation formula"],
  ["KYZc2", "libation formula"],
  ["MAZb8", "libation formula"],
  ["PKZa11", "libation formula"],
  ["PKZa12", "libation formula"],
  ["PKZa14", "religious objects"],
  ["PKZa15", "libation formula"],
  ["PKZa16", "religious objects"],
  ["PKZa17", "libation formula"],
  ["PKZa18", "libation formula"],
  ["PKZa4", "libation formula"],
  ["PKZa8", "libation formula"],
  ["PKZa9", "religious objects"],
  ["PKZc13", "religious objects"],
  ["PLZf1", "libation formula"],
  ["PLZf1", "written right to left"],
  ["PRZa1", "libation formula"],
  ["PSZa2", "libation formula"],
  ["SYZa1", "libation formula"],
  ["SYZa2", "religious contributions"],
  ["SYZa3", "libation formula"],
  ["TLZa1", "libation formula"],
  ["VRYZa1", "libation formula"],
  ["VRYZa1", "written right to left"],
  ["ZA15b", "wrong total"],
  ["ZAZb3", "libation formula"],
  ["ZAZb3", "religious contributions"],
  ["ARKH3a", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["ARKH3b", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT2", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT100", "violation of grain-cyperus, oil, olive, figs, wine word order"],
  ["HT101", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT114a", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT116a", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT116b", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT12", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT121", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT125a", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT125b", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT129", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT131a", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT131b", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT137", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT139", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT14", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT18", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT21", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT23a", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT23b", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT27a", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT27b", "violation of grain-cyperus, oil, olive, figs, wine word order"],
  ["HT28a", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT28b", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT30", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT30", "violation of grain-cyperus, oil, olive, figs, wine word order"],
  ["HT32", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT33", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT34", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT35", "violation of grain-cyperus, oil, olive, figs, wine word order"],
  ["HT44a", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT50a", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT58", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT90", "violation of grain-cyperus, oil, olive, figs, wine word order"],
  ["HT91", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT94a", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT96b", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT99a", "violation of grain-cyperus, oil, olive, figs, wine word order"],
  ["HT102", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT106", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT128a", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["HT130", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["KH5", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["KH8", "violation of grain-cyperus, oil, olive, figs, wine word order"],
  ["KH9", "violation of grain-cyperus, oil, olive, figs, wine word order"],
  ["KH9", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["KH11", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["KH12", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["KH21", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["KH55", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["KH61", "violation of grain-cyperus, oil, olive, figs, wine word order"],
  ["KNZb35", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["TY3a", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["ZA18a", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["ZA6a", "violation of grain-cyperus, oil, olive, figs, wine word order"],
  ["ZA6b", "uses grain-cyperus, oil, olive, figs, wine word order"],
  ["ZA11a", "uses grain-cyperus, oil, olive, figs, wine word order"],
];

var tags = new Map();
for (var tag of tagValues) {
  if (tags.has(tag[0])) {
    tags.get(tag[0]).push(tag[1]);
    continue;
  }
  tags.set(tag[0], [tag[1]]);
}

var periodNames = new Map([
["EM", "Pre-palace period 3500-1900 BCE"],
["EMI", "Early Minoan I  3500-2900 BCE"],
["EMII", "Early Minoan IIA, IIB  2900-2300 BCE"],
["EMIIIi", "Early Minoan III, Middle Minoan IA  2300-1900 BCE"],
["MHIII", "Middle Helladic 2000-1550 BCE"],
["MM", "Old Palace period 1900-1650 BCE"],
["MMI", "Middle Minoan I  1900-1800 BCE"],
["MMIA", "Middle Minoan IA  1900-1850 BCE"],
["MMIB", "Middle Minoan IB  1900-1800 BCE"],
["MMII", "Middle Minoan II  1800-1650 BCE"],
["MMIIA", "Middle Minoan IIA  1800-1750 BCE"],
["MMIIB", "Middle Minoan IIB, IIIA 1750-1650 BCE"],
["MMIII", "Middle Minoan III 1750-1600 BCE"],
["MMIIIA", "Middle Minoan IIB, IIIA 1750-1650 BCE"],
["NP",  "New Palace period 1650-1450 BCE"],
["MMIIIB", "(first) Middle Minoan IIIB  1650-1600 BCE"],
["LMI", "Late Minoan I 1600-1450 BCE"],
["LMIA", "Late Minoan IA 1600-1500 BCE"],
["LMIB", "Late Minoan IB  1500-1450 BCE"],
["CM",  "Creto-Mycenaean period  1450-1100 BCE"],
["LHI",  "1550-1450 BCE"],
["LBI",  "1550-1400 BCE"],
["LMII", "Third Palace period, Late Minoan II, IIIA1  1450-1350 BCE"],
["LMIII",  "Post Palace period. Late Minoan IIIA2, IIIB, IIIC 1400-1100 BCE"],
["LMIIIA",  "Post Palace period. Late Minoan IIIB 1350-1100 BCE"],
["SM",  "Sub-Minoan period 1100-1000 BCE"],
["Geometric",  "1000BCE"],
]);

var contexts = new Map();
for (var inscription of inscriptions.values()) {
  var key = inscription.name;
  var context = inscription.context;
  if (contexts.has(key)) {
    contexts.get(key).push(periodNames.get(context));
    continue;
  }
  if (!context) {
    continue;
  }
  if (!periodNames.has(context)) {
    console.log("Missing context: " + context);
  }
  contexts.set(key, [periodNames.get(context)]);
}

var grasses = ["𐙉", "𐛟","𐛬","𐛭","𐛮","𐛯","𐛱","𐛲","𐜠𐛱","𐙗","𐜙","𐜙","𐜚","𐜚","𐜛"];
var oilProducts = ["𐙖", "𐙜", "𐙘", "𐜉","𐜉","𐜊","𐜋","𐜋","𐜌","𐜍","𐜍","𐜎","𐜎","𐜏","𐜏",
                      "𐜐","𐜐","𐜑","𐜒","𐜓","𐜓","𐜔","𐜕","𐜖","𐜗","𐜗","𐜘"];
var MIProducts = ["𐘻","𐛚","𐛜","𐛜","𐛛","𐛙","𐛝"];
var vineProducts = ["𐙍","𐛾","𐙍","𐛽","𐙍","𐘞𐙍","𐛼","𐜀","𐜂", "𐛻","𐛿","𐜁","𐘋𐙍","𐙍𐘻"];
var QAProducts = ["𐚻","𐚹", "𐚻","𐚼","𐚹","𐚺","𐚻","𐚹","𐚻"];
var olive = ["𐙋"];
var figs = ["𐘝"];
var bronze = ["𐙈"];

var magazineRooms = new Map();
magazineRooms.set("57", {"x":61, "y":354, "width":58, "height":91});
magazineRooms.set("7a", {"x":372, "y":359, "width":41, "height":117});
magazineRooms.set("7", {"x":36, "y":486, "width":105, "height":23});
magazineRooms.set("17", {"x":477, "y":378, "width":106, "height":104});
magazineRooms.set("61", {"x":701, "y":445, "width":78, "height":87});
magazineRooms.set("8", {"x":711, "y":374, "width":72, "height":53});
magazineRooms.set("5", {"x":848, "y":314, "width":97, "height":137});
magazineRooms.set("findspot", {"x":699, "y":315, "width":33, "height":16});
magazineRooms.set("59", {"x":657, "y":193, "width":130, "height":117});
magazineRooms.set("58", {"x":415, "y":132, "width":140, "height":148});

var magazineRoomForProduct = new Map();
grasses.forEach(x => magazineRoomForProduct.set(x, "58"));
oilProducts.forEach(x => magazineRoomForProduct.set(x, "8"));
MIProducts.forEach(x => magazineRoomForProduct.set(x, "5"));
vineProducts.forEach(x => magazineRoomForProduct.set(x, "61"));
QAProducts.forEach(x => magazineRoomForProduct.set(x, "17"));
olive.forEach(x => magazineRoomForProduct.set(x, "58"));
figs.forEach(x => magazineRoomForProduct.set(x, "58"));
bronze.forEach(x => magazineRoomForProduct.set(x, "7a"));

var porticoRooms = new Map();
porticoRooms.set("findspot", {"x":280, "y":122, "width":75, "height":50});

var mainPlanRooms = new Map();
mainPlanRooms.set("9", {"x":613, "y":2322, "width":87, "height":93});

var casaDelLebeteRooms = new Map();
casaDelLebeteRooms.set("9", {"x":145, "y":126, "width":27, "height":32});
casaDelLebeteRooms.set("7", {"x":170, "y":75, "width":17, "height":41});

var maliaRooms = new Map();
maliaRooms.set("8",{"x":625, "y":1216, "width":114, "height":102});
maliaRooms.set("NW",{"x":1193, "y":773, "width":134, "height":106});
maliaRooms.set("E", {"x":1933, "y":1014, "width":114, "height":75});

var syllableValues = [
["𐘀", "DA"],
["𐘁", "RO"],
["𐘂", "PA"],
["𐘃", "TE"],
["𐘄", "TO"],
["𐘅", "NA"],
["𐘆", "DI"],
["𐘇", "A"],
["𐘈", "SE"],
["𐘉", "U"],
["𐘊", "PO"],
["𐘋", "ME"],
["𐘌", "QA"],
["𐘍", "ZA"],
["𐘎", "ZO"],
["𐘏", "QI"],
["𐘕", "MU"],
["𐘗", "NE"],
["𐘘", "RU"],
["𐘙", "RE"],
["𐘚", "I"],
["𐘜", "PU2"],
["𐘝", "NI"],
["𐘞", "SA"],
["𐘠", "TI"],
["𐘡", "E"],
["𐘢", "PI"],
["𐘣", "WI"],
["𐘤", "SI"],
["𐘥", "KE"],
["𐘦", "DE"],
["𐘧", "JE"],
["𐘩", "NWA"],
["𐘫", "PU"],
["𐘬", "DU"],
["𐘭", "RI"],
["𐘮", "WA"],
["𐘯", "NU"],
["𐘰", "PA3"],
["𐘱", "JA"],
["𐘲", "SU"],
["𐘳", "TA"],
["𐘴", "RA"],
["𐘵", "O"],
["𐘶", "JU"],
["𐘷", "TA2"],
["𐘸", "KI"],
["𐘹", "TU"],
["𐘺", "KO"],
["𐘻", "MI"],
["𐘼", "ZE"],
["𐘽", "RA2"],
["𐘾", "KA"],
["𐘿", "QE"],
["𐙁", "MA"],
["𐙂", "KU"],
["𐙄", "AU"],
["𐙆", "TWE"],
  ["𐘁", "RO"],
  ["𐘂", "PA"],
  ["𐘃", "TE"],
  ["𐘄", "TO"],
  ["𐘅", "NA"],
  ["𐘆", "DI"],
  ["𐘇", "A"],
  ["𐘈", "SE"],
  ["𐘉", "U"],
  ["𐘊", "PO"],
  ["𐘋", "ME"],
  ["𐘌", "QA"],
  ["𐘍", "ZA"],
  ["𐘎", "ZO"],
  ["𐘏", "QI"],
  ["𐘕", "MU"],
  ["𐘗", "NE"],
  ["𐘘", "RU"],
  ["𐘙", "RE"],
  ["𐘚", "I"],
  ["𐘜", "PU₂"],
  ["𐘝", "NI"],
  ["𐘞", "SA"],
  ["𐘠", "TI"],
  ["𐘡", "E"],
  ["𐘢", "PI"],
  ["𐘣", "WI"],
  ["𐘤", "SI"],
  ["𐘥", "KE"],
  ["𐘦", "DE"],
  ["𐘧", "JE"],
  ["𐘩", "NWA"],
  ["𐘫", "PU"],
  ["𐘬", "DU"],
  ["𐘭", "RI"],
  ["𐘮", "WA"],
  ["𐘯", "NU"],
  ["𐘰", "PA₂"],
  ["𐘱", "JA"],
  ["𐘲", "SU"],
  ["𐘳", "TA"],
  ["𐘴", "RA"],
  ["𐘵", "O"],
  ["𐘶", "JU"],
  ["𐘷", "TA₂"],
  ["𐘸", "KI"],
  ["𐘹", "TU"],
  ["𐘺", "KO"],
  ["𐘻", "MI"],
  ["𐘼", "ZE"],
  ["𐘽", "RA₂"],
  ["𐘾", "KA"],
  ["𐘿", "QE"],
  ["𐙁", "MA"],
  ["𐙂", "KU"],
  ["𐙄", "AU"],
  ["𐙆", "TWE"],
  ["𐘐", "*21F"],
  ["𐘑", "*21M"],
  ["𐘒", "*22"],
  ["𐘓", "*22F"],
  ["𐘔", "*22M"],
  ["𐘖", "*23M"],
  ["𐘛", "*28B"],
  ["𐘟", "*34"],
  ["𐘨", "*47"],
  ["𐘪", "*49"],
  ["𐙀", "*79"],
  ["𐙃", "*82"],
  ["𐙅", "*86"],
  ["𐙇", "*100-102"],
  ["𐙈", "*118"],
  ["𐙉", "*120"],
  ["𐙊", "*120B"],
  ["𐙋", "*122"],
  ["𐙌", "*123"],
  ["𐙍", "*131"],
  ["𐙎", "*131B"],
  ["𐙏", "*131C"],
  ["𐙐", "*164"],
  ["𐙑", "*171"],
  ["𐙒", "*180"],
  ["𐙓", "*188"],
  ["𐙔", "*191"],
  ["𐙕", "*301"],
  ["𐙖", "*302"],
  ["𐙗", "*303"],
  ["𐙘", "*304"],
  ["𐙙", "*305"],
  ["𐙚", "*306"],
  ["𐙛", "*307"],
  ["𐙜", "*308"],
  ["𐙝", "*309"],
  ["𐙞", "*309B"],
  ["𐙟", "*309C"],
  ["𐙠", "*310"],
  ["𐙡", "*311"],
  ["𐙢", "*312"],
  ["𐙣", "*313"],
  ["𐙤", "*313B"],
  ["𐙥", "*313C"],
  ["𐙦", "*314"],
  ["𐙧", "*315"],
  ["𐙨", "*316"],
  ["𐙩", "*317"],
  ["𐙪", "*318"],
  ["𐙫", "*319"],
  ["𐙬", "*320"],
  ["𐙭", "*321"],
  ["𐙮", "*322"],
  ["𐙯", "*323"],
  ["𐙰", "*324"],
  ["𐙱", "*325"],
  ["𐙲", "*326"],
  ["𐙳", "*327"],
  ["𐙴", "*328"],
  ["𐙵", "*329"],
  ["𐙶", "*330"],
  ["𐙷", "*331"],
  ["𐙸", "*332"],
  ["𐙹", "*333"],
  ["𐙺", "*334"],
  ["𐙻", "*335"],
  ["𐙼", "*336"],
  ["𐙽", "*337"],
  ["𐙾", "*338"],
  ["𐙿", "*339"],
  ["𐚀", "*340"],
  ["𐚁", "*341"],
  ["𐚂", "*342"],
  ["𐚃", "*343"],
  ["𐚄", "*344"],
  ["𐚅", "*345"],
  ["𐚆", "*346"],
  ["𐚇", "*347"],
  ["𐚈", "*348"],
  ["𐚉", "*349"],
  ["𐚊", "*350"],
  ["𐚋", "*351"],
  ["𐚌", "*352"],
  ["𐚍", "*353"],
  ["𐚎", "*354"],
  ["𐚏", "*355"],
  ["𐚐", "*356"],
  ["𐚑", "*357"],
  ["𐚒", "*358"],
  ["𐚓", "*359"],
  ["𐚔", "*360"],
  ["𐚕", "*361"],
  ["𐚖", "*362"],
  ["𐚗", "*363"],
  ["𐚘", "*364"],
  ["𐚙", "*365"],
  ["𐚚", "*366"],
  ["𐚛", "*367"],
  ["𐚜", "*368"],
  ["𐚝", "*369"],
  ["𐚞", "*370"],
  ["𐚟", "*371"],
  ["𐚠", "*400-VS"],
  ["𐚡", "*401-VS"],
  ["𐚢", "*402-VS"],
  ["𐚣", "*403-VS"],
  ["𐚤", "*404-VS"],
  ["𐚥", "*405-VS"],
  ["𐚦", "*406-VS"],
  ["𐚧", "*407-VS"],
  ["𐚨", "*408-VS"],
  ["𐚩", "*409-VS"],
  ["𐚪", "*410-VS"],
  ["𐚫", "*411-VS"],
  ["𐚬", "*412-VS"],
  ["𐚭", "*413-VS"],
  ["𐚮", "*414-VS"],
  ["𐚯", "*415-VS"],
  ["𐚰", "*416-VS"],
  ["𐚱", "*417-VS"],
  ["𐚲", "*418-VS"],
  ["𐚳", "*501"],
  ["𐚴", "*502"],
  ["𐚵", "*503"],
  ["𐚶", "*504"],
  ["𐚷", "*505"],
  ["𐚸", "*506"],
  ["𐘋𐙍", "*507"],
  ["𐚹", "*508"],
  ["𐚺", "*509"],
  ["𐚻", "*510"],
  ["𐚼", "*511"],
  ["𐚽", "*512"],
  ["𐚾", "*513"],
  ["𐘗𐘸", "*514"],
  ["𐚿", "*515"],
  ["𐛀", "*516"],
  ["𐘚𐛭", "*517"],
  ["𐘚𐙋", "*518"],
  ["𐘚𐙕", "*519"],
  ["𐛁", "*520"],
  ["𐛂", "*521"],
  ["𐘞𐙍", "*522"],
  ["𐛃", "*523"],
  ["𐛄", "*524"],
  ["𐛅", "*525"],
  ["𐛆", "*526"],
  ["𐛇", "*527"],
  ["𐛈", "*528"],
  ["𐛉", "*529"],
  ["𐛊", "*530"],
  ["𐛋", "*531"],
  ["𐛌", "*532"],
  ["𐘤𐙗", "*533"],
  ["𐛍", "*534"],
  ["𐛎", "*535"],
  ["𐛏", "*536"],
  ["𐛐", "*537"],
  ["𐛑", "*538"],
  ["𐛒", "*539"],
  ["𐛓", "*540"],
  ["𐛔", "*541"],
  ["𐛕", "*542"],
  ["𐘷𐙗", "*543"],
  ["𐛖", "*545"],
  ["𐘸𐙁𐘘", "*546"],
  ["𐛗", "*547"],
  ["𐛘", "*548"],
  ["𐛙", "*549"],
  ["𐛚", "*550"],
  ["𐛛", "*551"],
  ["𐛜", "*552"],
  ["𐛝", "*553"],
  ["𐛞", "*554"],
  ["𐛟", "*555"],
  ["𐛠", "*556"],
  ["𐛡", "*557"],
  ["𐛢", "*558"],
  ["𐛢", "*559"],
  ["𐛢", "*560"],
  ["𐙁𐘘𐘋", "*561"],
  ["𐙁𐘘𐘙", "*562"],
  ["𐛣", "*563"],
  ["𐛤", "*564"],
  ["𐛥", "*565"],
  ["𐛦", "*566"],
  ["𐙇", "*567"],
  ["𐛧", "*568"],
  ["𐛨", "*569"],
  ["𐛩", "*570"],
  ["𐛪", "*571"],
  ["𐛫", "*572"],
  ["𐛬", "*573"],
  ["𐛭", "*574"],
  ["𐛮", "*575"],
  ["𐛯", "*576"],
  ["𐛰", "*577"],
  ["𐛱", "*578"],
  ["𐛲", "*579"],
  ["𐛳", "*580"],
  ["𐛴", "*581"],
  ["𐛵", "*582"],
  ["𐛶", "*583"],
  ["𐛷", "*584"],
  ["𐛸", "*585"],
  ["𐛹", "*586"],
  ["𐛺", "*587"],
  ["𐛻", "*588"],
  ["𐛼", "*589"],
  ["𐙍𐘤", "*590"],
  ["𐛽", "*591"],
  ["𐛾", "*592"],
  ["𐙍𐘲", "*593"],
  ["𐛿", "*594"],
  ["𐜀", "*595"],
  ["𐜁", "*596"],
  ["𐙍𐙉", "*597"],
  ["𐜂", "*598"],
  ["𐙒", "*599"],
  ["𐜃", "*600"],
  ["𐜄", "*601"],
  ["𐜅", "*602"],
  ["𐜆", "*603"],
  ["𐜇", "*604"],
  ["𐝥𐘻", "*605"],
  ["𐜈", "*606"],
  ["𐝥𐚋", "*607"],
  ["𐜉", "*608"],
  ["𐜊", "*609"],
  ["𐜋", "*610"],
  ["𐜌", "*611"],
  ["𐜍", "*612"],
  ["𐜎", "*613"],
  ["𐜏", "*614"],
  ["𐜐", "*615"],
  ["𐜑", "*616"],
  ["𐜒", "*617"],
  ["𐜓", "*618"],
  ["𐜔", "*619"],
  ["𐜕", "*620"],
  ["𐜖", "*621"],
  ["𐜗", "*622"],
  ["𐜘", "*623"],
  ["𐜙", "*624"],
  ["𐙗𐝂𐜝", "*625"],
  ["𐜚", "*626"],
  ["𐜛", "*627"],
  ["𐜜", "*628"],
  ["𐜝", "*629"],
  ["𐜝𐙗𐝂", "*630"],
  ["𐜝𐙨𐝂", "*631"],
  ["𐙘𐙨", "*632"],
  ["𐙘𐙨", "*633"],
  ["𐜞", "*634"],
  ["𐙚𐙇𐙛", "*635"],
  ["𐙚𐙗𐝃", "*636"],
  ["𐜟", "*637"],
  ["𐜠", "*638"],
  ["𐙨𐘁𐙍", "*639"],
  ["𐜡", "*640"],
  ["𐙩𐘸𐙺", "*641"],
  ["𐜢", "*642"],
  ["𐜣", "*643"],
  ["𐜤", "*644"],
  ["𐜥", "*645"],
  ["𐜦", "*646"],
  ["𐚈𐙗", "*647"],
  ["𐜧", "*648"],
  ["𐜨", "*649"],
  ["𐚡𐘇", "*650"],
  ["𐜩", "*651"],
  ["𐜪", "*652"],
  ["𐜫", "*653"],
  ["𐜬", "*654"],
  ["𐜭", "*655"],
  ["𐜮", "*656"],
  ["𐜯", "*657"],
  ["𐜰", "*658"],
  ["𐜱", "*659"],
  ["𐜲", "*660"],
  ["𐜳", "*661"],
  ["𐜴", "*662"],
  ["𐜵", "*663"],
  ["𐜶", "*664"],
  ["𐝀", "*701"],
  ["𐝁", "*702B"],
  ["𐝂", "*703D"],
  ["𐝃", "*704E"],
  ["𐝄", "*705F"],
  ["𐝅", "*706H"],
  ["𐝆", "*707J"],
  ["𐝇", "*708K"],
  ["𐝈", "*709L"],
  ["𐝉", "*709-2L2"],
  ["𐝊", "*709-3L3"],
  ["𐝋", "*709-4L4"],
  ["𐝌", "*709-6L6"],
  ["𐝍", "*710W"],
  ["𐝎", "*711X"],
  ["𐝏", "*712Y"],
  ["𐝐", "*713Ω"],
  ["𐝑", "*714B"],
  ["𐝒", "*715BB"],
  ["𐝁𐝌", "*716BL6"],
  ["𐝓", "*717DD"],
  ["𐝂𐝂𐝂𐝂", "*718DDDD"],
  ["𐝃𐝁", "*719EB"],
  ["𐝃𐝃", "*720EE"],
  ["𐝃𐝄", "*721EF"],
  ["𐝃𐝆", "*722EJ"],
  ["𐝃𐝉", "*723EL2"],
  ["𐝃𐝋", "*724EL4"],
  ["𐝃𐝌", "*725EL6"],
  ["𐝔", "*726EYYY"],
  ["𐝄𐝇", "*727FK"],
  ["𐝄𐝈", "*728FL"],
  ["𐝅𐝇", "*729HK"],
  ["𐝆𐝀", "*730J"],
  ["𐝆𐝁", "*731JB"],
  ["𐝕", "*732JE"],
  ["𐝆𐝃𐝁", "*733JEB"],
  ["𐝆𐝃𐝉", "*734JEL2"],
  ["𐝆𐝄", "*735JF"],
  ["𐝆𐝅", "*736JH"],
  ["𐝆𐝆", "*737JJ"],
  ["𐝆𐝇", "*738JK"],
  ["𐝆𐝉", "*739JL2"],
  ["𐝇𐝉", "*740KL2"],
  ["𐝈𐝈", "*741LL"],
  ["𐝈𐝉", "*742LL2"],
  ["𐝉𐝋", "*743L2L4"],
  ["𐝠", "*800"],
  ["𐝡", "*801"],
  ["𐝢", "*802"],
  ["𐝣", "*803"],
  ["𐝤", "*804"],
  ["𐝥", "*805"],
  ["𐝦", "*806"],
  ["𐝧", "*807"],
  ["𐙇𐘍", "*808"],
  ["𐄁", "*900"],
  ["𐄀", "*901"],
  ["𐄀", "*902"],
  ["𐄂", "*903"],
  ["𐙫", "*904"],
  ["𐝆", "*905"],
  ["𐝇", "*906"],
  ["𐝬", "*809"],
  ["𐝭", "*810"],
  ["𐝮", "*811"],
  ["𐚢𐘌𐘰", "*812"],
  ["𐚯𐘲𐘫", "*813"],
  ["𐚰𐘾𐘁𐘰", "*814"],
  ["𐚢", "*815"],
  ["𐚢𐘲𐘰𐘴", "*816"],
  ["𐚢𐘂𐘳𐘿", "*817"],
  ["𐙞𐘸𐘫", "*818"],
  ["𐙝𐘀𐘫", "*819"],
  ["𐙝𐘶𐘸", "*820"],
  ["𐙝𐘭𐘶", "*821"],
  ["𐙟𐘀𐘶", "*822"],
  ["𐙟𐘘𐘾", "*823"],
  ["𐙝𐘭", "*824"],
  ["𐙞𐘭𐘶", "*825"],
  ["𐚥𐝇", "*826"],
  ["𐙄𐘤𐘙", "*827"],
  ["𐘮𐘃", "*828"],
  ["𐝯", "*829"],
];

var syllableToGlyph = new Map();
var glyphToSyllable = new Map();
for (var syllableValue of syllableValues) {
  var glyph = syllableValue[0];
  var syllable = syllableValue[1];
  if (!syllableToGlyph.has(key)) {
    syllableToGlyph.set(syllable, glyph);
  }
  if (!glyphToSyllable.has(key)) {
    glyphToSyllable.set(glyph, syllable);
  }
}

