var identicalWords = new Map([
["KI-RO", ['KN X 8838']],
["MA-DI", ['KN As(1) 603', 'KN Db 1168', 'TH Fq 285']],
["PA-RE", ['KN Dl(1) 8177', 'KN Sc 247', 'KN Sc 249']],
["WI-DU", ['KN V(7) 1523', 'KN As(2) 1517']],
["KA-PA", ['TH Ft 217', 'TH Ft 234', 'TH Ft 219', 'TH Ft 220', 'KN E(1) 71', 'TH Ft 141', 'TH Ft 151', 'PY Un 138', 'TH Ft 268', 'PY Xn 1111', 'TH Ft 143', 'PY Ua 9']],
["SA-MA", ['MY Ge 602', 'KN X 9323', 'KN X 7845', 'PY On 300', 'KN X 9434']],
["TA-NA-TI", ['KN Uf(1) <311>']],
["PA-DE", ['KN Fs 8', 'KN Ga(3) 456', 'KN C 394', 'KN Fp(1) 1', 'KN Fp(1) 48']],
["A-SI", ['PY Cn 254']],
["RE-ZA", ['TH Fq 120']],
["KA-NA", ['KN Ra(1) 1552']],
["KO-RU", ['KN Sk 8254', 'TH Fq 254', 'KN Sk 8100', 'TH Fq 126']],
["I-TA-JA", ['KN Ap 769', 'KN Xe 537']],
["PU-KO", ['KN Dv 9590']],
["KU-RE", ['KN X 7668']],
["PA-JA", ['KN V(3) 503', 'KN Uf(1) 111']],
["RE-TE", ['PY Jo 438']],
["KI-DA-RO", ['KN E 842']],
["SI-RA", ['KN B(1) 988', 'KN X 7744']],
["RI-JA", ['KN X 9901']],
["MI-TI", ['KN Dl(1) 463']],
["KA-TI", ['PY Tn 996', 'KN Ce 76']],
["A-SE", ['PY An 852']],
["A-DU", ['KN X 9312', 'KN L(6) 460']],
["TE-KE", ['PY Ta 711']],
["DI-DE", ['KN B(5) 799']],
["A-RA", ['KN Wb 5131', 'KN Ra(1) 1550']],
["TA-RA", ['KN Am(2) 821', 'KN Xd 8034']],
["I-KA", ['KN X 7502']],
["TU-MA", ['KN X 8282']],
["PA-I-TO", ['KN Sd 4413', 'KN Dd 1429', 'KN E 36', 'KN Db 1464', 'KN Da 1164', 'KN L(6) 469', 'KN X 522', 'KN X 7546', 'KN Dv 5075', 'KN Da 1352', 'KN Dv 1509', 'KN Dd 1157', 'KN Da 1163', 'KN Da 1378', 'KN Dv 1607', 'KN Da 1495', 'KN Db 1159', 'KN Pp 498', 'KN X 7629', 'KN Dg 1158', 'KN Dd 1342', 'KN Ga(2) 416', 'KN Da 1170', 'KN Dm 1180', 'KN Od 765', 'KN Da 1172', 'KN Db 1507', 'KN X 697', 'KN Da 1161', 'KN Db 1344', 'KN Dv 1085', 'KN Wb 2001', 'KN So(1) 4448', 'KN Dn 1094', 'KN X <1474>', 'KN Dq(3) 7852', 'KN Da 1156', 'KN De 1084', 'KN Da 1173', 'KN Dd 1171', 'KN Od 502', 'KN U 1539', 'KN Xf 5104', 'KN Da 8201', 'KN Dd 5174', 'KN F(2) 841', 'KN Db 1160']],
["MA-*79", ['PY Eo 276', 'PY En 74']],
["KU-PA", ['KN X 7770', 'KN Ga(3) 454']],
["QA-SA", ['KN Dq(3) 8351', 'KN Fh 6001', 'KN X 5178']],
["WI-SA", ['PY Cn 328']],
["PA-RA-NE", ['KN Vc(1) 7616']],
["KU-TA", ['KN X 5534', 'KN X 9443', 'KN Dv 1490']],
["U-SU", ['KN V(3) 7512']],
["MI-TA", ['MY Ge 602', 'MY Ge 606', 'MY Ge 605']],
["MA-RI", ['KN Dl(1) 947', 'KN X 7828', 'KN X 5970', 'KN Dl(1) 948', 'KN Ga(1) 7594']],
["MI-KA", ['KN L(9) 8035', 'PY Fn 970']],
["A-RI", ['PY Wa 931']],
["KA-SI", ['TH Ft 234', 'TH Ft 219', 'TH Ft 220', 'TH Ft 141', 'TH Fq 205', 'TH Ft 268', 'TH Ft 143']],
["RE-RO", ['PY Cn 491']],
["KA-SA", ['PY Cn 202', 'TH Gp 158']],
["A-TA", ['PY An 39']],
["QA-NE", ['PY Xa 176']],
["PA-TA", ['MY L 710', 'KN Vc(1) 7540', 'KN C(4) 917', 'TH Fq 254', 'PY Cn 40']],
["KU-KA", ['MY Oe 121']],
["RU-NA", ['PY Un 1320', 'KN As(2) 1516']],
["A-KA-TA", ['PY En 659']],
["PU-RA", ['KN B(5) 804', 'KN V(6) 958', 'KN L(2) 593']],
["NU-SE", ['KN X 9190', 'TI X 1']],
["NI-PI", ['PY Cn 962']],
["I-JA", ['KN Xd 105', 'KN Ap 628', 'KN X 9238', 'KN Do 7087']],
["A-PI", ['KN X 5040', 'PY Ep 539', 'PY Ta 716', 'KN G 820']],
["DA-MA-TE", ['PY En 609']],
["A-MA", ['KN E 1035', 'KN F(2) 845', 'KN F(2) 852', 'KN E 850', 'KN As(1) 608', 'KN E 848', 'KN F(2) 851', 'KN X 9687']],
["A-JA", ['KN X 9521']],
["E-KA", ['KN Dm 5181']],
["TO-ME", ['PY Ep 613']],
["A-NU", ['KN U 4478', 'KN V(7) 1521', 'TI Z 8']],
["I-NA", ['PY Ep 539', 'PY Fn 837', 'PY Eb 885']],
["DA-RA", ['MY Ge 603', 'KN X 8750']],
["MA-TE-RE", ['PY Fr 1202']],
["WI-JA", ['KN As(2) 1518', 'PY An 615', 'KN U 1812', 'KN C(2) 941']],
["DU-RI", ['KN Da 1143']],
["SU-KI-RI-TA", ['KN Db 1327', 'KN Dv 5232', 'KN Df 1325', 'KN Da 1091', 'KN Db 1324', 'KN Dn 1092']],
["SI-MA", ['PY En 609', 'PY Eo 211']],
["I-JA-TE", ['PY Eq 146']],
["I-PI", ['PY Cn 595']],
["TO-SA", ['PY Na 924', 'KN Mc 4457', 'KN Od(1) 688', 'KN Ap 5868', 'PY Sa 787', 'KN X 1047', 'KN Ld(1) 587', 'KN Ld(1) 584', 'KN X 8614', 'KN Dl(1) 7086', 'PY En 609', 'KN L(10) 7409', 'KN X 7574', 'PY Xn 888', 'PY Er 880', 'KN Ga(5) 1530', 'PY Sa 843', 'KN X 450', 'KN X 7581', 'KN C(4) 917', 'KN Lc(1) 535', 'KN Ap 639', 'KN Ld(1) 598', 'KN Ra(1) 1540', 'KN Ln 1568', 'KN Dp 997', 'TH X 105']],
["RE-JA", ['PY Eb 173', 'KN Ai(2) 752', 'KN L 5987', 'KN L 7382']],
["SE-TO-I-JA", ['KN Wm 8493', 'KN Do 7740', 'KN Lc(1) 525', 'KN Da 1392', 'KN X 5040', 'KN Sd 4407', 'KN X 660', 'KN Mc 4464', 'KN Ak(1) 634', 'KN Dq(4) 686', 'KN Do 1054', 'KN Le 654', 'KN As(2) 1516', 'KN As 40', 'KN Am 5755', 'KN Dq(4) 438']],
["TE-JA", ['KN X 8833']],
["MI-JA", ['KN X 8312', 'KN X 8526']],
["RO-QA", ['TH Fq 229', 'KN Fh <376>']],
["WA-TE", ['KN Fh 9074', 'KN X 5594']],
["A-NE", ['KN Xd 7757']],
["A-RE", ['KN X 5716', 'KN Fp(1) 14', 'KN Xd 9126', 'PY Cn 485', 'KN Mc 4462']],
["E-MI", ['TH Gp 237']],
["DA-I-PI-TA", ['KN B(5) 799']],
["SA-RI", ['PY An 31']],
["DI-KI", ['KN Xd 7651', 'KN Dv 5775']],
["KA-NE", ['TH Ft 182']],
["JA-PI", ['KN Sd <4450>']],
["NI-TA", ['KN Ap 5748']],
["A-RO-TE", ['PY La 622']],
]);
var identicalRoots = new Map([
["MA-SI", ['KN E 850', 'KN Fh 360']],
["DA-TA", ['KN Dl(1) 935']],
["WA-DU", ['KN C(4) 912', 'KN Db 1242', 'KN V(3) 503', 'KN Dc 1118', 'KN Ga(3) 456', 'KN V(7) 1523', 'KN Da 1445', 'KN Dk(2) 1491', 'PY Jn 725', 'KN As(2) 1516']],
["RA-TI", ['KN E(2) 668', 'KN B(5) 802', 'KN X 7754']],
["QE-TI", ['MY Wt 504', 'MY Ue 611']],
["TE-TU", ['PY Nn 228', 'PY Sa 682', 'KN L 871', 'PY Na 1054']],
["DA-RU", ['KN Uf 432']],
["SI-KI", ['KN U 8210', 'KN Da 1339']],
["TA-I", ['TH Ug 13', 'KN Da 8201']],
["A-RU", ['KN Dv 8652']],
["KU-RO", ['PY Un 616']],
["KU-NI", ['KN B 798']],
["ME-ZA", ['PY An 610', 'PY Cn 3', 'PY Un 138', 'KN Sc 222', 'PY Fn 50', 'PY Sh 736']],
["QA-TI", ['KN Fh 355', 'KN As(2) 1519']],
["DA-I", ['KN Da 1164', 'KN Da 1317', 'KN Do 996', 'KN De 1231', 'PY Aq 218', 'KN V(3) 479', 'KN B(5) 799', 'KN V(5) 1043', 'KN Od 7388', 'TH Ug 15', 'KN Xd 8128']],
["KA-U", ['TH Z 839', 'KN U 4478', 'KN Fs 21', 'PY An 340', 'PY Jn 832']],
["TE-KI", ['KN Dq(4) 686']],
["A-PU2", ['PY Vn 20', 'KN Xd <331>', 'PY An 657', 'PY Jn 693', 'PY Jo 438', 'PY An 427', 'KN Uf(1) 111', 'PY Qa 1294', 'PY An 656', 'PY Cn 608', 'PY Ma 124', 'PY Jn 829']],
["SI-DA", ['KN Gg(3) 717', 'KN Dl(1) 947', 'KN Nc 4490', 'KN Od(1) 562']],
["PA-SE", ['MY Oe 121']],
["KU-MA", ['KN V(3) 7512', 'TH Fq 137']],
["KI-MA", ['PY Ad 668', 'PY Aa 63', 'KN As(2) 1520', 'KN V(3) 7620']],
["MA-RU", ['PY En 609']],
["I-TI", ['KN Dq(1) 439']],
["TA-TI", ['PY An 654', 'KN X 7894', 'PY An 724']],
["TI-NI", ['KN Dl(1) 9716', 'PY Ep 613', 'PY An 1281', 'PY Fn 79']],
["I-MI", ['KN Db 1186']],
["KI-DA", ['KN So 894', 'KN E 842']],
["SA-RA", ['PY Er 880', 'PY Un 718']],
["RU-MA", ['KN Dg 1438']],
["KI-TA", ['KN Da 1108', 'KN Am(2) 821', 'KN Ga(5) 1530', 'KN Ga(5) 1532', 'PY Vn 1339', 'KN X 1385']],
["TI-SA", ['OR Z 1']],
["I-KU", ['MY Oi 705', 'KN L 588', 'KN V(2) 280']],
["KA-KI", ['KN So 894']],
["RA-NA", ['PY Xa 1382']],
["SU-KI", ['KN Db 1327', 'KN Dv 5232', 'KN X 7562', 'KN C(4) 911', 'KN Dl 47', 'KN Df 1325', 'KN Da 1091', 'KN As(2) 1516', 'KN Db 1324', 'KN Dn 1092']],
["KU-MI", ['KN X 8154', 'MY Ge 602', 'KN X 459', 'MY Ge 605', 'KN Da 1202']],
["MA-RE", ['MA Z 1', 'PY An 657', 'PY Eo 276', 'PY En 74']],
["TA-MI", ['PY Na 248', 'KN Fs 11', 'PY Jn 310', 'KN Dl(1) 944']],
["KA-RU", ['PY Ad 671', 'PY Ta 721', 'PY Ta 722', 'KN Dl(1) 412', 'TH Wu 55', 'KH Z 1', 'KN Dl(1) 7147', 'PY Fn 187', 'PY Un 219']],
["RI-SU", ['MY V 659']],
["KI-KI", ['KN Da 1435']],
["A-TU", ['KN K(1) 877', 'PY En 609', 'KN V(7) 1523', 'PY Ep 301', 'KN Dg 1102', 'PY Eo 211', 'KN B(5) 799', 'PY Jn 725', 'PY Jn 927', 'PY Jn 658']],
["A-SA", ['PY Mn 162', 'PY Sa 761', 'PY Cn 1287', 'KN Ws 8497', 'KN X <748>', 'PY Na 523', 'KN As 40']],
["MA-I", ['PY An 661']],
["TE-RI", ['PY Un 443', 'TH Gp 157']],
["DI-RI", ['PY An 830', 'PY Tn 316']],
["QA-QA", ['KN As(1) 604']],
["O-TI", ['PY Ab 417', 'TH Fq 306', 'PY Cn 285', 'TH Fq 276', 'TH Fq 275', 'TH Fq 229', 'TH Fq 247', 'PY Aa 313', 'PY Ad 663']],
["DE-DI", ['KN Ak(1) 611']],
["DE-ME", ['PY An 35']],
["A-PA", ['KN Gg(3) 5185', 'PY Na 551', 'PY Na 246', 'PY Jn 845', 'KN Dv 5224', 'PY Cn 286', 'PY Cn 643', 'KN L 588', 'KN B(5) 804', 'KN Xd <320>', 'PY Sa 767', 'KN Am(2) 826', 'KN C 902', 'KN Co 909', 'KN V(5) 7670', 'KN Fh 9070', 'PY Jn 927', 'KN Ce 144', 'KN X 7669', 'PY Cn 719']],
["SI-MI", ['TH Av 106', 'KN As(1) 607', 'KN V(5) 1583', 'MY Ge 602', 'KN Am(2) 827', 'MY Ge 606']],
["RU-SA", ['KN Ln 1568']],
["KA-NU", ['KN As(1) 602', 'PY An 129']],
["KA-RI", ['KN As(1) 609', 'PY Jn 706', 'MY Au 102', 'PY Jn 431', 'KN As(2) 1516', 'KN X 7918']],
["DA-KU", ['KN L 870']],
["KI-RA", ['KN V(5) 1005', 'KN Fh 360', 'MY V 659']],
["TA-PA", ['PY Vn 493', 'KN F(1) 153', 'KN As(1) 608', 'KN B 823', 'KN X 7795', 'KN Sc 240', 'KN X 5346']],
["PA-DA", ['PY Eb 159', 'PY An 192', 'PY Eo 444', 'PY Eb 499', 'PY Eb 839', 'PY Eb 1347']],
["QA-RU", ['MY Au 660', 'MY Au 657']],
["RA-RI", ['KN C(4) 911', 'KN Dl(1) 7905']],
["PA-RA", ['PY Cn 655', 'TH Wu 46', 'PY Vn 20', 'KN Se 879', 'KN Db 1373', 'PY Eq 36', 'KN Sk 789', 'PY Eo 224', 'PY Fn 324', 'KN Vc(1) 7616', 'TH Of 34', 'PY Sa 787', 'PY Sh 740', 'PY Cn 200', 'PY Eb 377', 'PY An 298', 'KN Ld(1) 575', 'KN Sp 4451', 'PY Ep 301', 'PY Eb 173', 'KN U(1) 109', 'PY Jn 750', 'PY Ta 642', 'PY Ep 613', 'PY Na 197', 'PY Vn 1314', 'KN U(1) 124', 'PY Cn 254', 'KN C(2) 914', 'KN Sc 258', 'PY Ta 715', 'KN Sk 8100', 'PY Jn 832', 'PY Ta 714', 'PY Sa 793', 'KN Ln 1568', 'PY Cn 40', 'PY An 37', 'PY Un 219', 'PY Sh 737', 'PY Cn 719', 'KN Xf 5102']],
["NU-WI", ['PY Fr 1255']],
["A-I", ['PY Eo 471', 'PY En 659', 'PY Ep 301', 'PY Eb 895']],
["QA-NU", ['KN As(2) 1516', 'KN Fh <389>']],
["KU-RA", ['KN As(2) 1517']],
["MI-RU", ['KN C 902', 'KN Da 1127', 'KN As(2) 1516', 'KN V(3) 482', 'KN V(4) 5913']],
["KU-KU", ['KN X <8204>']],
["KO-SA", ['PY Ep 212', 'KN Ga(1) 685', 'PY An 615', 'PY Eb 915']],
["DA-NE", ['PY Cn 655']],
["RI-MI", ['KN E 4466', 'KN Og 833', 'KN E 749']],
["DA-U", ['TH Fq 269', 'PY Cn 1287', 'PY Jn 431', 'KN Do 9793']],
["JA-MI", ['KN Ap 5547', 'KN X 8072']],
["KU-DA", ['PY Es 652', 'PY Es 650', 'PY Es 644', 'KN V(5) 1004', 'KN L 523']],
["TI-DA", ['KH Z 23']],
["PI-SA", ['KN B 1055']],
["A-NA", ['KN Pp 494', 'PY Ub 1315', 'KN Sf(1) 4427', 'PY Jn 415', 'KN Sg 888', 'KN Sf(1) 4421', 'KN Sf(2) 4425', 'KN Sf 7450', 'KN Xd 7570', 'KN Sf(2) 4420', 'KN Nc 4480', 'KN Sf(1) 4423', 'PY Aq 218', 'KN Sf(2) 4465', 'KN Dv 1471', 'KN B 798', 'MY Fo 101', 'KN Sf 7723', 'PY Un 219', 'KN Sf 7451', 'KN Sf(2) 4419']],
["DU-NE", ['TI Z 30']],
["TU-RU", ['TI X 6', 'KN X 986', 'PY Un 443', 'PY An 35', 'PY An 261', 'PY Cn 254']],
["QA-RE", ['KN Dl(1) 7132']],
["PU-MA", ['PY Cn 643', 'KN Dv 6045']],
["TU-ME", ['MY Ui 709']],
["DA-KA", ['PY An 172', 'PY Gn 720']],
["TA-NI", ['PY An 657', 'KN Og 833', 'PY An 1281']],
["WA-DI", ['PY Fn 79']],
["NA-MA", ['PY Cn 1287']],
["TA-JA", ['KN Dv 7240']],
["JA-SA", ['KN V(6) 832', 'KN As(2) 1516', 'KN Ce 152']],
["DA-DA", ['KN X 723', 'KN Fs <32>', 'KN Fp(1) 1', 'KN Fp(1) 18']],
["WI-NA", ['KN Da 1197', 'KN Df 5198', 'KN X 5750', 'KN Db 1225', 'KN Dv 1330', 'KN Z 1716', 'KN K(1) 875', 'ARM Z 1', 'MI Z 4', 'KN X 9909', 'KN Db 1282', 'KN Fh 1059']],
["TA-TA", ['PY Cn 655', 'PY Eb 874', 'KN As(1) 607', 'PY Eo 224', 'PY Ep 301', 'KN Xd 8605', 'KN Ce 152']],
["I-SI", ['TH Gp 127']],
["I-PA", ['KN Db 7172', 'PY Eb 1345', 'PY Eo 247']],
["DU-RE", ['PY Jn 845']],
["SI-NA", ['KN Fh 5471']],
["TA-U", ['KN X 1478', 'KN V(6) 832', 'KN U 4478', 'KN Ga(2) 417', 'KN Dv 8357', 'KN E 843', 'KN De 1269']],
["RA-KI", ['KN X 7791']],
["A-DI", ['PY Ta 707', 'PY Ta 708', 'KN Do 7613', 'KN D 747', 'PY Ta 714', 'KN F(2) 841', 'KN D 5520', 'KN As(2) 1517']],
["A-DA", ['KN Da 5223', 'PY Eb 747', 'KN C(4) 912', 'PY En 659', 'PY Aa 785', 'PY Ab 388', 'PY Ep 301', 'KN B(4) 164', 'PY An 656', 'PY Aq 218', 'PY Eo 351', 'PY Jn 832', 'KN X 793']],
["NA-KI", ['KN Wm 8499']],
["I-ZA", ['KN B(5) 805', 'PY Fn 50']],
["PA-RI", ['PY Na 514']],
["JA-RA", ['KN De 1424']],
["TA-NU", ['KN Fh 5456', 'PY An 209']],
["DA-WA", ['KN Ga(2) 423', 'KN Mc 4461', 'KN As(2) 1517']],
["WI-PI", ['KN V(6) 958', 'KN X 8838', 'KN Nc 5103']],
["I-WA", ['PY An 519', 'PY Cn 655', 'PY An 654', 'KN V(2) 60', 'PY Cn 3', 'KN Xd 7756', 'KN Uf(1) 120', 'PY Jn 310', 'PY An 661', 'PY Ub 1317', 'KN As(2) 1516']],
["KE-SI", ['KN Xd <335>']],
["O-DA", ['PY Aq 64', 'KN So(1) 4440', 'KN So(2) 4446', 'PY Ma 393', 'PY Ma 397', 'PY En 659', 'KN So(1) 4430', 'PY Wa 917', 'PY Ma 221', 'PY Eq 213', 'PY Ma 193', 'PY Eq 36', 'PY Ed 847', 'PY Eq 146', 'PY Ma 123', 'PY Ma 90', 'PY Ma 365', 'KN So 894', 'PY Ed 317', 'PY An 435', 'KN Sg 1811', 'PY En 609', 'KN So(1) 4436', 'KN B(4) 164', 'PY Aq 218', 'PY Ma 378', 'PY Ma 225', 'KN So(1) 4432', 'PY Un 718', 'PY En 74', 'PY Ma 124', 'KN So 4435', 'PY Ed 901', 'PY Ma 120', 'KN V(4) 5913', 'KN So(1) 4441']],
["QA-MI", ['KN Dv 8280', 'KN Lc(1) 543', 'KN Ap 5876', 'KN Og 833', 'KN Le 641', 'KN E 749', 'KN Ak(2) 613', 'KN Sc 135']],
["TA-TE", ['PY An 209']],
["I-DA", ['KN Xd <332>', 'KN Xd 154', 'TH Of 28', 'KN K(1) 875', 'PY An 661']],
["JA-MA", ['KN V(3) 503', 'KN V(3) 655']],
["DU-PI", ['KN Vc(1) 287']],
["QE-SI", ['KN Ld(1) 583']],
["A-KU", ['KN Fh 364', 'KN Xd 110', 'KN As(1) 609', 'PY Sa 287', 'KN Xd 112', 'KN Ce 139', 'KN U(1) 109', 'KN Dc 1270']],
["RA-O", ['KN Dv 1249']],
["A-MI", ['KN Ga(3) 465', 'KN L(5) 513', 'KN Sc 7476', 'KN X 9015', 'KN Fp(1) 14', 'KN Sc 237', 'KN V(7) 1526', 'KN Gg(3) 705', 'KN Vc(1) 289', 'KN Lc(1) 550', 'KN E 777', 'KN Ai(3) 1036', 'KN Am(1) 601', 'KN X <1641>', 'KN X 435', 'KN Ra(1) 1543', 'KN Ga 953', 'PY An 233', 'KN M 719', 'KN X 410', 'KN Od(1) 687', 'KN Od(2) 718', 'KN V(3) 7512', 'KN Fh 5451', 'KN Le 654', 'KN Lc(1) 5053', 'KN Fp(1) 1', 'KN V(1) 114', 'KN V(3) 482', 'KN Fp(1) 48', 'PY Vn 865', 'PY Cn 436', 'KN Sc 252', 'KN Ai(3) 825', 'KN As(2) 1520', 'KN Ak(1) 638']],
["TI-NA", ['PY Jn 601']],
["NE-TI", ['TH Av 106', 'PY Cn 599', 'PY Cn 40']],
["MA-TI", ['KN D 1024', 'KN V(6) 831', 'KN Xd 209', 'KN Vc(1) <295>', 'KN X 5074']],
["DU-PU2", ['KN V(3) 479', 'KN Da 1173', 'KN Fh 343']],
["JA-PA", ['KN V(4) 652', 'KN V(3) 429']],
["TE-ME", ['PY Er 312', 'KN Xd <319>']],
["SI-NI", ['KN X 7848', 'KN Dg 1280']],
["NE-KI", ['KN Ak(3) 780', 'KN Od(1) 687', 'KN Ws 8152', 'KN Ln 1568']],
["PI-KU", ['PY La 631']],
["KA-DI", ['KN V(5) 9320', 'KN Vc(1) 9128', 'KN V(5) 1003']],
["KI-NI", ['KN Xd 7547', 'PY Aa 792', 'PY An 292', 'PY Ad 683', 'PY Ab 189']],
["O-TA", ['KN E 1035', 'KN Xd 7547', 'MY Oe 111', 'MY Fo 101']],
["I-SE", ['KN Dd 5105', 'KN L(3) 473', 'KN Xd 7675', 'KN B 798']],
["PU2-RA2", ['PY Nn 228', 'PY Na 425']],
["PA-ZA", ['KN Dl(1) 948']],
["I-MA", ['PY Ea 29', 'PY Jn 310', 'PY Cn 436', 'PY Ea 816']],
["KU-TU", ['KN Da 1161', 'KN Ap 639']],
["RO-SI", ['PY Na 197', 'PY An 261']],
["WI-RA", ['KN Dv 1205', 'KN Da 5193', 'KN As(2) 1516']],
["A-DE", ['PY Eq 36', 'PY Eq 146', 'PY An 207', 'KN As(2) 1516', 'KN Ap 639']],
["RA-MA", ['PY Jn 692', 'PY Cn 285', 'KN Ai(2) 762', 'PY Ub 1316', 'KN Fh 353', 'PY Jn 725']],
["E-KU", ['MY Wt 501']],
["ME-KI", ['PY Fr 1244', 'PY Aa 955', 'KN Dv 1434', 'KN Xe 537', 'PY Ab 575']],
["KU-PI", ['KN Gg(2) 995', 'KN Fp(2) 5472', 'KN Fh 5447', 'KN Fh 5490', 'KN Fh 347', 'KN X 468', 'PY Cn 131', 'KN Ga(1) 676', 'KN Fh 371', 'KN Ga(1) 677', 'KN Fh 5446', 'PY Un 443', 'KN Fh 5246', 'KN K(2) 773', 'KN Ga(1) 517', 'PY Jn 320', 'KN Fh 372', 'KN Fh 361', 'PY Cn 719']],
["TU-MI", ['MY Fo 101']],
["*47-KU", ['KN Fp(1) 13']],
["RA-TE", ['KN V(4) 653', 'PY Xa 1384']],
["TE-TE", ['PY Jn 389', 'PY Eb 1176', 'PY Ep 539', 'KN V(6) 958']],
["O-MI", ['KN Fh 356', 'KN C(4) 911']],
["PU2-RE", ['TH Of 26', 'KN Sc 243']],
["NA-SI", ['KN B(5) 800']],
["KI-NU", ['KN B(1) 772', 'KN Ap 618', 'PY Qa 1301', 'PY Vn 865']],
["PI-TI", ['PY Ta 713']],
["DE-MI", ['PY Wr 1326', 'PY Un 1482', 'KN Fh 5431', 'PY Vn 851', 'MY V 659']],
]);
var similarWords = new Map([
["KI-RO", "KI-JO"],
["KI-RO", "KO-RO"],
["KI-RO", "-KI-RO"],
["KI-RO", "KE-RO"],
["KI-RO", "KI-ZO"],
["KI-RO", "KI-TO"],
["KI-RO", "KA-RO"],
["KI-RO", "DI-RO"],
["KI-RO", "TI-RO"],
["KI-RO", "KI-RI"],
["KI-RO", "RI-RO"],
["KI-RO", "PI-RO"],
["KI-RO", "WI-RO"],
["KI-RO", "KI-SO"],
["A-RA-NA-RE", "A-RA-NA-RO"],
["A-KA-RU", "A-RA-RU"],
["DI-NA", "DI-DA"],
["DI-NA", "I-NA"],
["DI-NA", "DI-KA"],
["DI-NA", "DI-PA"],
["DI-NA", "DI-ZA"],
["DI-NA", "DA-NA"],
["DI-NA", "DI-RA"],
["MU-RU", "KU-RU"],
["MU-RU", "PU-RU"],
["MU-RU", "DU-RU"],
["MA-DI", "MA-RI"],
["MA-DI", "MA-KI"],
["MA-DI", "MA-DI-"],
["PA-RE", "PA-RO"],
["PA-RE", "PA-DE"],
["PA-RE", "A-RE"],
["PA-RE", "PA-RU"],
["PA-RE", "PE-RE"],
["PA-RE", "PA-WE"],
["PA-RE", "PA-TE"],
["PA-RE", "KA-RE"],
["PA-RE", "PA-ZE"],
["MA-SI", "PA-SI"],
["MA-SI", "KA-SI"],
["MA-SI", "MA-SA"],
["MA-SI", "MA-RI"],
["MA-SI", "MA-DI"],
["MA-SI", "MA-KI"],
["MA-SI", "MA-SE"],
["MA-SI", "ME-SI"],
["MA-SI", "TA-SI"],
["MA-SI", "A-SI"],
["WI-DU", "I-DU"],
["KA-PA", "KA-MA"],
["KA-PA", "KA-KA"],
["KA-PA", "KA-TA"],
["KA-PA", "KA-RA"],
["KA-PA", "KU-PA"],
["KA-PA", "SA-PA"],
["KA-PA", "KA-NA"],
["KA-PA", "KA-ZA"],
["KA-PA", "KA-PO"],
["KA-PA", "KA-SA"],
["KA-PA", "KA-JA"],
["KA-PA", "RA-PA"],
["DA-TA-RA", "A-TA-RA"],
["DA-TA-RA", "KA-TA-RA"],
["PI-TA-JA", "I-TA-JA"],
["PI-TA-JA", "PA-TA-JA"],
["KA-PA-QE", "TA-PA-QE"],
["KA-PA-QE", "KA-PA-RE"],
["QE-PI-TA", "E-PI-TA"],
["QE-PI-TA", "QE-RI-TA"],
["DA-KI", "PA-KI"],
["DA-KI", "A-KI"],
["DA-KI", "DA-MI"],
["DA-KI", "DI-KI"],
["DA-KI", "MA-KI"],
["DA-KI", "DA-WI"],
["SA-MA", "A-MA"],
["SA-MA", "KA-MA"],
["SA-MA", "SA-ME"],
["SA-MA", "SA-PA"],
["SA-MA", "DA-MA"],
["SA-MA", "SI-MA"],
["SA-MA", "SA-QA"],
["SA-MA", "SA-SA"],
["SA-MA", "SA-MU"],
["SA-MA", "SA-MI"],
["QE-TI", "QE-TE"],
["QE-TI", "QE-TO"],
["QE-TI", "QE-RI"],
["QE-TI", "ME-TI"],
["I-RU-JA", "I-RI-JA"],
["DU-JA", "DU-MA"],
["TA-NA-TI", "TA-NA-TO"],
["TA-NA-TI", "JA-NA-TI"],
["DA-RE", "A-RE"],
["DA-RE", "DA-RO"],
["DA-RE", "PA-RE"],
["DA-RE", "DA-RA"],
["DA-RE", "KA-RE"],
["DA-RE", "DO-RE"],
["DA-RE", "DA-WE"],
["TE-TU", "TO-TU"],
["TE-TU", "ME-TU"],
["TE-TU", "TE-U"],
["TE-TU", "TI-TU"],
["TE-TU", "TE-NU"],
["TE-TU", "TE-TO"],
["TE-TU", "TE-RU"],
["TE-TU", "TE-TA"],
["SI-KI-RA", "SI-KI-RO"],
["PA-JA-RE", "PA-TA-RE"],
["PA-JA-RE", "PA-JA-RO"],
["SA-RO", "PA-RO"],
["SA-RO", "NA-RO"],
["SA-RO", "SA-JO"],
["SA-RO", "DA-RO"],
["SA-RO", "KA-RO"],
["SA-RO", "A-RO"],
["SA-RO", "MA-RO"],
["SA-RO", "TA-RO"],
["SA-RO", "SO-RO"],
["SA-RO", "JA-RO"],
["SA-RO", "SA-RI"],
["SA-RO", "SA-TO"],
["SA-RO", "SA-ZO"],
["SA-RO", "SA-NO"],
["SA-RO", "SA-SO"],
["SA-RO", "RA-RO"],
["PA-DE", "RA-DE"],
["PA-DE", "KA-DE"],
["PA-DE", "PA-WE"],
["PA-DE", "PA-RE"],
["PA-DE", "SA-DE"],
["PA-DE", "PA-TE"],
["PA-DE", "PO-DE"],
["PA-DE", "JA-DE"],
["PA-DE", "PA-ZE"],
["PA-DE", "WA-DE"],
["QE-PU", "KE-PU"],
["QE-PU", "ZE-PU"],
["QE-PU", "QE-U"],
["A-RU", "A-RE"],
["A-RU", "A-DU"],
["A-RU", "I-RU"],
["A-RU", "PA-RU"],
["A-RU", "A-PU"],
["A-RU", "A-RO"],
["A-RU", "A-NU"],
["A-RU", "-RU"],
["A-RU", "JA-RU"],
["A-RU", "E-RU"],
["A-RU", "A-RI"],
["A-RU", "A-RA"],
["A-RU", "A-RU-"],
["A-RU", "NA-RU"],
["KU-RO", "KU-NO"],
["KU-RO", "PU-RO"],
["KU-RO", "KO-RO"],
["KU-RO", "RU-RO"],
["KU-RO", "KU-RU"],
["KU-RO", "KE-RO"],
["KU-RO", "KA-RO"],
["KU-RO", "KU-RO2"],
["KU-RO", "KU-DO"],
["KU-RO", "KU-JO"],
["KU-RO", "KU-SO"],
["KU-RO", "KU-WO"],
["KU-RO", "DU-RO"],
["KU-RO", "TU-RO"],
["KU-RO", "KU-TO"],
["KU-RO", "KU-PO"],
["KU-RO", "KI-RO"],
["KU-RO", "KU-RE"],
["KU-RO", "AU-RO"],
["A-SI", "-SI"],
["A-SI", "PA-SI"],
["A-SI", "KA-SI"],
["A-SI", "A-PI"],
["A-SI", "A-KI"],
["A-SI", "A-TI"],
["A-SI", "A-RI"],
["A-SI", "A-SE"],
["A-SI", "A-QI"],
["A-SI", "TA-SI"],
["ME-ZA", "ME-ZO"],
["ME-ZA", "ME-NA"],
["ME-ZA", "RE-ZA"],
["ME-ZA", "ME-RA"],
["ME-ZA", "ME-ZA-"],
["ME-ZA", "ME-TA"],
["ME-ZA", "PE-ZA"],
["ME-ZA", "ME-JA"],
["U-TI", "TU-TI"],
["U-TI", "PU-TI"],
["U-TI", "MU-TI"],
["U-TI", "U-TA"],
["U-TI", "-TI"],
["U-TI", "A-TI"],
["U-TI", "U-TE"],
["KA-SA-RU", "KA-SA-RO"],
["A-SU-JA", "A-U-JA"],
["DE-NU", "TE-NU"],
["DE-NU", "DE-U"],
["DE-NU", "KE-NU"],
["RU-RA2", "RU-A2"],
["RU-RA2", "RU-TA2"],
["DA-I", "DA-"],
["DA-I", "PA-I"],
["DA-I", "RA-I"],
["DA-I", "DA-MI"],
["DA-I", "DA-WI"],
["DA-I", "DA-I-"],
["RE-ZA", "RO-ZA"],
["RE-ZA", "RE-WA"],
["RE-ZA", "RE-TA"],
["RE-ZA", "RE-KA"],
["RE-ZA", "RE-JA"],
["RE-ZA", "PE-ZA"],
["RE-ZA", "RE-A"],
["TE-KI", "TE-MI"],
["TE-KI", "E-KI"],
["TE-KI", "KE-KI"],
["TE-KI", "TE-KE"],
["TE-KI", "TE-I"],
["SA-PO", "SA-JO"],
["SA-PO", "SU-PO"],
["SA-PO", "A-PO"],
["SA-PO", "NA-PO"],
["SA-PO", "SA-PA"],
["SA-PO", "SA-PI"],
["SA-PO", "WA-PO"],
["SA-PO", "KA-PO"],
["SA-PO", "SA-TO"],
["SA-PO", "SA-ZO"],
["SA-PO", "SA-NO"],
["SA-PO", "JA-PO"],
["SA-PO", "SA-SO"],
["PA-SE", "PA-DE"],
["PA-SE", "PA-SI"],
["PA-SE", "PA-WE"],
["PA-SE", "PA-RE"],
["PA-SE", "PA-TE"],
["PA-SE", "PO-SE"],
["PA-SE", "A-SE"],
["PA-SE", "PA-SA"],
["PA-SE", "MA-SE"],
["PA-SE", "JA-SE"],
["PA-SE", "PA-ZE"],
["SA-RA2", "QA-RA2"],
["SA-RA2", "TA-RA2"],
["KA-NA", "KA-PA"],
["KA-NA", "KA-NO"],
["KA-NA", "KO-NA"],
["KA-NA", "KA-MA"],
["KA-NA", "KA-KA"],
["KA-NA", "KA-TA"],
["KA-NA", "KU-NA"],
["KA-NA", "KA-RA"],
["KA-NA", "QA-NA"],
["KA-NA", "KA-NI"],
["KA-NA", "PA-NA"],
["KA-NA", "KA-ZA"],
["KA-NA", "KA-NE"],
["KA-NA", "WA-NA"],
["KA-NA", "KA-SA"],
["KA-NA", "KA-JA"],
["KA-NA", "DA-NA"],
["KA-NA", "TA-NA"],
["SA-SA-ME", "SA-SA-MA"],
["KO-RU", "KO-RO"],
["KO-RU", "KU-RU"],
["KO-RU", "RO-RU"],
["KO-RU", "KO-U"],
["KO-RU", "KO-RI"],
["KO-RU", "KO-RA"],
["KO-RU", "KO-RU-"],
["KO-RU", "KO-DU"],
["KO-RU", "KO-TU"],
["KO-RU", "KO-KU"],
["KO-RU", "KO-PU"],
["NI-RA", "NI-JA"],
["NI-RA", "MI-RA"],
["NI-RA", "NI-TA"],
["NI-RA", "TI-RA"],
["NI-RA", "SI-RA"],
["NI-RA", "DI-RA"],
["KI-MA-RU", "KI-MA-RA"],
["RU-I-KO", "RO-I-KO"],
["RU-NI", "RU-I"],
["RU-NI", "RU-KI"],
["RU-NI", "TU-NI"],
["RU-NI", "RU-NA"],
["RU-NI", "RU-SI"],
["RU-NI", "DU-NI"],
["RU-NI", "RA-NI"],
["RU-NI", "RU-NU"],
["U-RE-WI", "U-RE-WE"],
["DU-RU-WI", "DU-RU-WO"],
["I-KI-RA", "O-KI-RA"],
["I-TI", "-TI"],
["I-TI", "I-TO"],
["I-TI", "RI-TI"],
["I-TI", "I-QI"],
["I-TI", "A-TI"],
["I-TI", "I-TA"],
["I-TI", "MI-TI"],
["I-TI", "KI-TI"],
["I-TI", "I-PI"],
["TA-TI", "TU-TI"],
["TA-TI", "PA-TI"],
["TA-TI", "TA-TO"],
["TA-TI", "KA-TI"],
["TA-TI", "A-TI"],
["TA-TI", "TA-SI"],
["TA-TI", "JA-TI"],
["RO-NI", "RO-PI"],
["RO-NI", "TO-NI"],
["RO-NI", "WO-NI"],
["RO-NI", "RA-NI"],
["RO-NI", "RO-NO"],
["TI-NI-TA", "TI-NI-JA"],
["KI-DA", "KI-JA"],
["KI-DA", "DI-DA"],
["KI-DA", "KI-DE"],
["KI-DA", "KI-SA"],
["MI-DA", "MI-RA"],
["MI-DA", "MI-KA"],
["MI-DA", "DI-DA"],
["MI-DA", "MI-TA"],
["MI-DA", "MI-JA"],
["MI-DA", "MU-DA"],
["MI-DA", "MO-DA"],
["I-TA-JA", "U-TA-JA"],
["PU-RA2", "PE-RA2"],
["PU-RA2", "PU-RA"],
["RU-MA-TA", "RE-MA-TA"],
["KI-TA", "KI-JA"],
["KI-TA", "KA-TA"],
["KI-TA", "PI-TA"],
["KI-TA", "NI-TA"],
["KI-TA", "KI-TO"],
["KI-TA", "KE-TA"],
["KI-TA", "MI-TA"],
["KI-TA", "QI-TA"],
["KI-TA", "KO-TA"],
["KI-TA", "RI-TA"],
["KI-TA", "KU-TA"],
["KI-TA", "KI-SA"],
["KI-TA", "I-TA"],
["KI-TA", "KI-TI"],
["KI-TA", "KI-TE"],
["SA-RA-RA", "SA-DA-RA"],
["SA-RA-RA", "SA-MA-RA"],
["TI-SA", "TO-SA"],
["TI-SA", "TI-RA"],
["TI-SA", "TI-JA"],
["TI-SA", "WI-SA"],
["TI-SA", "TI-MA"],
["TI-SA", "TI-SE"],
["TI-SA", "TI-ZA"],
["TI-SA", "KI-SA"],
["PU-KO", "PU-RO"],
["PU-KO", "SU-KO"],
["PU-KO", "PU-WO"],
["PU-KO", "PU-SO"],
["PU-KO", "PU-ZO"],
["PU-KO", "PE-KO"],
["PU-KO", "MU-KO"],
["PU-KO", "PU-KA"],
["PU-KO", "PA-KO"],
["PU-KO", "PI-KO"],
["PU-KO", "RU-KO"],
["PU-KO", "PU-KE"],
["PU-KO", "U-KO"],
["SA-JA-MA", "SI-JA-MA"],
["SA-JA-MA", "SA-SA-MA"],
["SU-RE", "SU-RI"],
["SU-RE", "U-RE"],
["SU-RE", "SO-RE"],
["SU-RE", "KU-RE"],
["SU-RE", "SU-SE"],
["SU-RE", "SU-RA"],
["I-KU-TA", "I-KU-TO"],
["I-KU-TA", "I-KE-TA"],
["KA-KI", "KA-KE"],
["KA-KI", "KA-KO"],
["KA-KI", "KA-SI"],
["KA-KI", "KA-KA"],
["KA-KI", "PA-KI"],
["KA-KI", "KA-WI"],
["KA-KI", "KE-KI"],
["KA-KI", "KA-NI"],
["KA-KI", "KA-TI"],
["KA-KI", "A-KI"],
["KA-KI", "MA-KI"],
["KA-KI", "KO-KI"],
["RE-SU", "RA-SU"],
["RE-SU", "RE-U"],
["RE-SU", "RE-SI"],
["DA-RO-PA", "A-RO-PA"],
["SA-MA-TI", "A-MA-TI"],
["KU-RE", "KU-NE"],
["KU-RE", "KU-RU"],
["KU-RE", "U-RE"],
["KU-RE", "KE-RE"],
["KU-RE", "KA-RE"],
["KI-DA-TA", "KI-DA-PA"],
["KI-DA-TA", "KI-PA-TA"],
["KI-DA-TA", "KI-MA-TA"],
["QE-TU", "ME-TU"],
["QE-TU", "QE-TE"],
["QE-TU", "QE-TO"],
["QE-TU", "QE-U"],
["PA-JA", "WA-JA"],
["PA-JA", "RA-JA"],
["PA-JA", "PA-TA"],
["PA-JA", "PA-KA"],
["PA-JA", "PI-JA"],
["PA-JA", "PA-NA"],
["PA-JA", "PA-SA"],
["PA-JA", "KA-JA"],
["PA-JA", "A-JA"],
["RE-TE", "RE-TO"],
["RE-TE", "RE-TA"],
["RE-TE", "E-TE"],
["RE-TE", "RE-KE"],
["RE-TE", "RE-WE"],
["RE-TE", "QE-TE"],
["RE-TE", "RE-NE"],
["RE-TE", "ME-TE"],
["RE-TE", "-RE-TE"],
["KI-DA-RO", "KI-WA-RO"],
["KI-DA-RO", "KI-DO-RO"],
["KI-DA-RO", "KI-DU-RO"],
["KI-DA-RO", "KA-DA-RO"],
["SU-KI", "SU-KO"],
["SU-KI", "RU-KI"],
["SU-KI", "SU-RI"],
["SU-KI", "SU-MI"],
["SI-RA", "SI-RA-"],
["SI-RA", "MI-RA"],
["SI-RA", "TI-RA"],
["SI-RA", "SI-MA"],
["SI-RA", "SI-JA"],
["SI-RA", "SI-QA"],
["SI-RA", "SI-ZA"],
["SI-RA", "SU-RA"],
["SI-RA", "DI-RA"],
["I-KI", "E-KI"],
["I-KI", "-KI"],
["I-KI", "A-KI"],
["I-KI", "I-QI"],
["I-KI", "DI-KI"],
["I-KI", "I-KA"],
["I-KI", "NI-KI"],
["I-KI", "I-PI"],
["I-KI", "O-KI"],
["TI-NI", "TI-NO"],
["TI-NI", "TI-RI"],
["TI-NI", "TU-NI"],
["TI-NI", "TO-NI"],
["SA-NE", "SA-ME"],
["SA-NE", "A-NE"],
["SA-NE", "SA-DE"],
["SA-NE", "KA-NE"],
["SA-NE", "QA-NE"],
["SA-NE", "SA-NO"],
["SA-NE", "MA-NE"],
["MA-RE", "A-RE"],
["MA-RE", "MA-RI"],
["MA-RE", "MA-RO"],
["MA-RE", "MA-RA"],
["MA-RE", "PA-RE"],
["MA-RE", "MA-WE"],
["MA-RE", "MA-TE"],
["MA-RE", "MA-SE"],
["MA-RE", "KA-RE"],
["MA-RE", "MA-NE"],
["MA-RE", "MA-QE"],
["MA-RE", "MO-RE"],
["SI-RU", "I-RU"],
["SI-RU", "PI-RU"],
["SI-RU", "SI-RA"],
["RI-JA", "NI-JA"],
["RI-JA", "QI-JA"],
["RI-JA", "KI-JA"],
["RI-JA", "-I-JA"],
["RI-JA", "RA-JA"],
["RI-JA", "RI-JO"],
["RI-JA", "RI-KA"],
["RI-JA", "PI-JA"],
["RI-JA", "TI-JA"],
["RI-JA", "MI-JA"],
["RI-JA", "RI-TA"],
["RI-JA", "RI-WA"],
["RI-JA", "WI-JA"],
["RI-JA", "RE-JA"],
["RI-JA", "SI-JA"],
["RI-JA", "-RI-JA"],
["RI-JA", "I-JA"],
["RI-JA", "RI-MA"],
["U-KI", "U-KA"],
["U-KI", "RU-KI"],
["U-KI", "E-KI"],
["U-KI", "-KI"],
["U-KI", "A-KI"],
["U-KI", "U-KO"],
["U-KI", "U-KE"],
["U-KI", "O-KI"],
["MI-TI", "MU-TI"],
["MI-TI", "MI-TA"],
["MI-TI", "RI-TI"],
["MI-TI", "KI-TI"],
["MI-TI", "ME-TI"],
["KA-KU", "KA-KE"],
["KA-KU", "KA-KO"],
["KA-KU", "KA-KA"],
["KA-KU", "RA-KU"],
["KA-KU", "KO-KU"],
["KA-KU", "MA-KU"],
["SA-RA", "QA-RA"],
["SA-RA", "KA-RA"],
["SA-RA", "SA-PA"],
["SA-RA", "SA-MA"],
["SA-RA", "MA-RA"],
["SA-RA", "SI-RA"],
["SA-RA", "TA-RA"],
["SA-RA", "SA-RI"],
["SA-RA", "DA-RA"],
["SA-RA", "SA-QA"],
["SA-RA", "A-RA"],
["SA-RA", "SA-SA"],
["SA-RA", "SU-RA"],
["KA-TI", "KA-SI"],
["KA-TI", "KA-TA"],
["KA-TI", "KA-TE"],
["KA-TI", "KA-TI-"],
["KA-TI", "KA-WI"],
["KA-TI", "PA-TI"],
["KA-TI", "KA-NI"],
["KA-TI", "KA-TO"],
["KA-TI", "KO-TI"],
["KA-TI", "A-TI"],
["KA-TI", "KI-TI"],
["KA-TI", "JA-TI"],
["SU-PU2", "SI-PU2"],
["RU-MA", "RU-KA"],
["RU-MA", "U-MA"],
["RU-MA", "RU-WA"],
["RU-MA", "RU-NA"],
["RU-MA", "DU-MA"],
["RU-MA", "RI-MA"],
["RU-MA", "TU-MA"],
["TA-MI", "TE-MI"],
["TA-MI", "DA-MI"],
["TA-MI", "TA-SI"],
["TA-MI", "SA-MI"],
["KA-RU", "KU-RU"],
["KA-RU", "KA-RA"],
["KA-RU", "KA-RO"],
["KA-RU", "PA-RU"],
["KA-RU", "JA-RU"],
["KA-RU", "KO-RU"],
["KA-RU", "KA-RE"],
["KA-RU", "NA-RU"],
["KU-NI", "KU-NO"],
["KU-NI", "KU-NE"],
["KU-NI", "TU-NI"],
["KU-NI", "KU-NA"],
["KU-NI", "KA-NI"],
["KU-NI", "DU-NI"],
["KU-NI", "KU-SI"],
["JU-RA", "PU-RA"],
["JU-RA", "-U-RA"],
["JU-RA", "U-RA"],
["JU-RA", "JE-RA"],
["JU-RA", "SU-RA"],
["A-SE", "A-E"],
["A-SE", "A-RE"],
["A-SE", "-SE"],
["A-SE", "A-ME"],
["A-SE", "A-NE"],
["A-SE", "E-SE"],
["A-SE", "A-WE"],
["A-SE", "A-KE"],
["A-SE", "A-TE"],
["A-SE", "MA-SE"],
["A-SE", "JA-SE"],
["A-SE", "A-SI"],
["RI-SU-MA", "RI-SU-RA"],
["NU-TI", "TU-TI"],
["NU-TI", "PU-TI"],
["NU-TI", "MU-TI"],
["NU-TI", "NU-TO"],
["A-DU", "-DU"],
["A-DU", "A-PU"],
["A-DU", "A-NU"],
["A-DU", "A-DU-"],
["A-DU", "O-DU"],
["A-DU", "I-DU"],
["TE-KE", "E-KE"],
["TE-KE", "TE-RE"],
["TE-KE", "KE-KE"],
["TE-KE", "TE-WE"],
["TE-KE", "RE-KE"],
["TE-KE", "WE-KE"],
["TE-KE", "TE-JE"],
["TE-KE", "TE-PE"],
["QE-KA", "QE-RA"],
["QE-KA", "QA-KA"],
["QE-KA", "RE-KA"],
["QE-KA", "E-KA"],
["SA-RU", "PA-RU"],
["SA-RU", "SA-RI"],
["SA-RU", "JA-RU"],
["SA-RU", "SA-MU"],
["SA-RU", "NA-RU"],
["DI-DE-RU", "DI-DE-RO"],
["QA-RA2-WA", "QA-RA2-WO"],
["DA-ME", "DA-MO"],
["DA-ME", "NA-ME"],
["DA-ME", "SA-ME"],
["DA-ME", "A-ME"],
["DA-ME", "DA-MA"],
["DA-ME", "DA-MI"],
["DA-ME", "DA-WE"],
["DI-DE", "DI-DA"],
["DI-DE", "DI-WE"],
["DI-DE", "DO-DE"],
["DI-DE", "DI-JE"],
["DI-DE", "KI-DE"],
["DI-DE", "DE-DE"],
["KU-RU-KU", "KU-RU-KA"],
["A-RA", "A-MA"],
["A-RA", "-RA"],
["A-RA", "QA-RA"],
["A-RA", "E-RA"],
["A-RA", "A-RE"],
["A-RA", "A-TA"],
["A-RA", "A-WA"],
["A-RA", "KA-RA"],
["A-RA", "A-RO"],
["A-RA", "A-KA"],
["A-RA", "MA-RA"],
["A-RA", "TA-RA"],
["A-RA", "DA-RA"],
["A-RA", "A-RI"],
["A-RA", "U-RA"],
["A-RA", "O-RA"],
["A-RA", "A-JA"],
["A-TU", "WA-TU"],
["A-TU", "A-TA"],
["A-TU", "A-DU"],
["A-TU", "A-PU"],
["A-TU", "A-NU"],
["A-TU", "A-TE"],
["A-TU", "A-TI"],
["A-TU", "RA-TU"],
["A-TU", "A-TO"],
["A-TU", "O-TU"],
["KA-JU", "KA-JA"],
["KA-JU", "KA-JO"],
["SA-MA-RO", "MA-MA-RO"],
["SA-MA-RO", "SA-MA-RA"],
["SA-MA-RO", "SA-ZA-RO"],
["SA-MA-RO", "SA-MA-RU"],
["DA-TA-RE", "PA-TA-RE"],
["DA-TA-RE", "DA-DA-RE"],
["TA-RA", "QA-RA"],
["TA-RA", "TA-RA-"],
["TA-RA", "TI-RA"],
["TA-RA", "KA-RA"],
["TA-RA", "TE-RA"],
["TA-RA", "TA-ZA"],
["TA-RA", "MA-RA"],
["TA-RA", "TA-RO"],
["TA-RA", "TO-RA"],
["TA-RA", "DA-RA"],
["TA-RA", "A-RA"],
["TA-RA", "TA-RA2"],
["TA-RA", "TA-NA"],
["I-KA", "O-KA"],
["I-KA", "U-KA"],
["I-KA", "RI-KA"],
["I-KA", "MI-KA"],
["I-KA", "-KA"],
["I-KA", "A-KA"],
["I-KA", "I-NA"],
["I-KA", "DI-KA"],
["I-KA", "E-KA"],
["I-KA", "I-TA"],
["I-KA", "I-JA"],
["I-KA", "PI-KA"],
["TE-RI", "TI-RI"],
["TE-RI", "TE-RE"],
["TE-RI", "TE-MI"],
["TE-RI", "TE-RO"],
["TE-RI", "TU-RI"],
["TE-RI", "TE-RA"],
["TE-RI", "ME-RI"],
["TE-RI", "PE-RI"],
["TE-RI", "TE-I"],
["TE-RI", "E-RI"],
["TE-RI", "QE-RI"],
["TE-RI", "TE-RU"],
["QA-QA-RU", "QA-QA-RO"],
["O-TI", "DO-TI"],
["O-TI", "O-PI"],
["O-TI", "-TI"],
["O-TI", "O-TE"],
["O-TI", "PO-TI"],
["O-TI", "KO-TI"],
["O-TI", "A-TI"],
["O-TI", "O-TO"],
["O-TI", "O-TU"],
["O-TI", "O-KI"],
["PA-SE-JA", "PA-SA-JA"],
["TU-MA", "U-MA"],
["TU-MA", "TI-MA"],
["TU-MA", "DU-MA"],
["TU-MA", "TO-MA"],
["PA-TA-NE", "PA-TA-RE"],
["PA-TA-NE", "PA-RA-NE"],
["DE-DI", "DE-DE"],
["SI-MI-TA", "SI-MI-JA"],
["SI-MI-TA", "SI-MU-TA"],
["RU-SA", "RU-KA"],
["RU-SA", "RU-WA"],
["RU-SA", "RU-NA"],
["RU-SA", "RU-SI"],
["PI-TA-RA", "PI-ZA-RA"],
["KU-MA-RO", "KU-PA-RO"],
["KU-MA-RO", "KU-KA-RO"],
["KU-MA-RO", "KU-MA-TO"],
["KU-MA-RO", "KU-JA-RO"],
["TE-NI", "E-NI"],
["TE-NI", "TE-MI"],
["TE-NI", "TU-NI"],
["TE-NI", "TO-NI"],
["TE-NI", "TE-NU"],
["TE-NI", "TE-I"],
["NA-TI", "NA-TO"],
["NA-TI", "PA-TI"],
["NA-TI", "KA-TI"],
["NA-TI", "A-TI"],
["NA-TI", "NA-NI"],
["NA-TI", "JA-TI"],
["NA-TI", "NA-PI"],
["RO-KE", "DO-KE"],
["RO-KE", "RO-KA"],
["RO-KE", "RA-KE"],
["RO-KE", "RE-KE"],
["RO-KE", "RO-WE"],
["RO-KE", "RO-KO"],
["RO-KE", "WO-KE"],
["KU-PA3", "KU-PA"],
["MA-*79", "A-*79"],
["U-TA2", "U-TA"],
["U-TA2", "-TA2"],
["U-TA2", "RU-TA2"],
["U-TA2", "AU-TA2"],
["U-TA2", "I-TA2"],
["KI-RA", "KI-JA"],
["KI-RA", "MI-RA"],
["KI-RA", "TI-RA"],
["KI-RA", "KA-RA"],
["KI-RA", "KE-RA"],
["KI-RA", "KO-RA"],
["KI-RA", "SI-RA"],
["KI-RA", "KI-RI"],
["KI-RA", "KI-SA"],
["KI-RA", "KI-RO"],
["KI-RA", "DI-RA"],
["TA-PA", "KA-PA"],
["TA-PA", "TE-PA"],
["TA-PA", "TA-ZA"],
["TA-PA", "SA-PA"],
["TA-PA", "TA-RA"],
["TA-PA", "TO-PA"],
["TA-PA", "TA-PA-"],
["TA-PA", "RA-PA"],
["TA-PA", "TA-NA"],
["DI-NA-RO", "DA-NA-RO"],
["DU-SU-NI", "DU-SA-NI"],
["A-RA-JU", "A-RA-RU"],
["KU-PA", "KA-PA"],
["KU-PA", "KU-NA"],
["KU-PA", "KU-KA"],
["KU-PA", "KU-TA"],
["KU-PA", "KU-PO"],
["QA-SA", "QA-RA"],
["QA-SA", "MA-SA"],
["QA-SA", "QA-KA"],
["QA-SA", "QA-NA"],
["QA-SA", "PA-SA"],
["QA-SA", "KA-SA"],
["QA-SA", "SA-SA"],
["QA-RU", "QA-RA"],
["QA-RU", "PA-RU"],
["QA-RU", "JA-RU"],
["QA-RU", "NA-RU"],
["SA-DI", "SA-PI"],
["SA-DI", "SA-DE"],
["SA-DI", "SA-RI"],
["SA-DI", "MA-DI"],
["SA-DI", "SA-MI"],
["TU-PA", "TE-PA"],
["TU-PA", "KU-PA"],
["TU-PA", "TO-PA"],
["TU-PA", "TU-MA"],
["WI-SA", "WI-JA"],
["WI-SA", "KI-SA"],
["WI-SA", "WI-SO"],
["KI-RI-TA2", "KI-RI-TA"],
["PA-RA-NE", "MA-RA-NE"],
["A-SE-JA", "A-ME-JA"],
["A-SE-JA", "A-RE-JA"],
["A-SE-JA", "-SE-JA"],
["TI-NU-JA", "TI-NI-JA"],
["NU-WI", "NU-WO"],
["NU-WI", "NU-WE"],
["NU-WI", "NE-WI"],
["KU-RU-MA", "KU-RU-KA"],
["A-I", "A-"],
["A-I", "-I"],
["A-I", "A-E"],
["A-I", "A-PI"],
["A-I", "PA-I"],
["A-I", "RA-I"],
["A-I", "A-KI"],
["A-I", "A-TI"],
["A-I", "A-RI"],
["A-I", "A-QI"],
["A-I", "A-SI"],
["KU-TA", "KA-TA"],
["KU-TA", "KU-NA"],
["KU-TA", "U-TA"],
["KU-TA", "KU-PA"],
["KU-TA", "KE-TA"],
["KU-TA", "KU-KA"],
["KU-TA", "KU-TA-"],
["KU-TA", "KO-TA"],
["KU-TA", "PU-TA"],
["KU-TA", "KU-TO"],
["U-TA-RO", "U-TE-RO"],
["U-TA-RO", "U-TA-JO"],
["U-TA-RO", "U-TA-NO"],
["U-TA-RO", "A-TA-RO"],
["U-TA-RO", "-TA-RO"],
["KU-PA-JA", "KU-NA-JA"],
["KU-PA-JA", "KU-PA-SA"],
["U-SU", "U-SO"],
["U-SU", "KU-SU"],
["U-SU", "-SU"],
["MI-TU", "MI-TA"],
["MI-TU", "ME-TU"],
["MI-TU", "TI-TU"],
["MI-TU", "MI-TI"],
["MA-RU", "PA-RU"],
["MA-RU", "MA-PU"],
["MA-RU", "MA-RI"],
["MA-RU", "MA-RO"],
["MA-RU", "MA-RA"],
["MA-RU", "JA-RU"],
["MA-RU", "NA-RU"],
["MA-RU", "MA-KU"],
["TE-JA-RE", "TE-JA-RO"],
["NA-DA-RE", "DA-DA-RE"],
["SA-TA", "PA-TA"],
["SA-TA", "A-TA"],
["SA-TA", "KA-TA"],
["SA-TA", "SA-PA"],
["SA-TA", "SA-MA"],
["SA-TA", "SA-TO"],
["SA-TA", "MA-TA"],
["SA-TA", "SA-QA"],
["SA-TA", "SA-SA"],
["SA-TA", "WA-TA"],
["SA-TA", "-SA-TA"],
["DA-MI-NU", "JA-MI-NU"],
["DA-MI-NU", "DA-MI-NI"],
["KO-JA", "KO-WA"],
["KO-JA", "KI-JA"],
["KO-JA", "KO-NA"],
["KO-JA", "KO-RA"],
["KO-JA", "KO-MA"],
["KO-JA", "KO-TA"],
["KO-JA", "KA-JA"],
["KO-JA", "KO-A"],
["KO-JA", "KO-JO"],
["KO-JA", "KE-JA"],
["RA-RI", "RA-WI"],
["RA-RI", "MA-RI"],
["RA-RI", "RA-I"],
["RA-RI", "RA-NI"],
["RA-RI", "SA-RI"],
["RA-RI", "A-RI"],
["RA-RI", "RA-RO"],
["KU-DA", "KU-NA"],
["KU-DA", "KU-PA"],
["KU-DA", "KU-KA"],
["KU-DA", "KU-DO"],
["KU-DA", "KU-TA"],
["KU-DA", "MU-DA"],
["DA-TU", "WA-TU"],
["DA-TU", "DA-PU"],
["DA-TU", "RA-TU"],
["TI-DA-TA", "TI-DA-TO"],
["PI-SA", "PI-MA"],
["PI-SA", "PI-TA"],
["PI-SA", "PI-JA"],
["PI-SA", "WI-SA"],
["PI-SA", "KI-SA"],
["PI-SA", "PA-SA"],
["PI-SA", "PI-KA"],
["SI-DU", "WI-DU"],
["SI-DU", "I-DU"],
["RE-TA2", "RE-TA"],
["RE-TA2", "RU-TA2"],
["A-NA", "A-MA"],
["A-NA", "O-NA"],
["A-NA", "-NA"],
["A-NA", "A-TA"],
["A-NA", "A-WA"],
["A-NA", "A-NE"],
["A-NA", "QA-NA"],
["A-NA", "A-NU"],
["A-NA", "A-KA"],
["A-NA", "PA-NA"],
["A-NA", "KA-NA"],
["A-NA", "I-NA"],
["A-NA", "WA-NA"],
["A-NA", "A-RA"],
["A-NA", "A-NO"],
["A-NA", "DA-NA"],
["A-NA", "E-NA"],
["A-NA", "A-JA"],
["A-NA", "TA-NA"],
["SI-DI-JA", "SI-NI-JA"],
["SI-DI-JA", "SI-MI-JA"],
["PA-RA", "PA-RO"],
["PA-RA", "QA-RA"],
["PA-RA", "PA-TA"],
["PA-RA", "PA-KA"],
["PA-RA", "KA-RA"],
["PA-RA", "PA-RU"],
["PA-RA", "PA-JA"],
["PA-RA", "PA-NA"],
["PA-RA", "MA-RA"],
["PA-RA", "PA-RE"],
["PA-RA", "TA-RA"],
["PA-RA", "PU-RA"],
["PA-RA", "DA-RA"],
["PA-RA", "PE-RA"],
["PA-RA", "PA-RA-"],
["PA-RA", "PA-SA"],
["PA-RA", "A-RA"],
["MI-TA", "MO-TA"],
["MI-TA", "MI-RA"],
["MI-TA", "PI-TA"],
["MI-TA", "MI-KA"],
["MI-TA", "NI-TA"],
["MI-TA", "ME-TA"],
["MI-TA", "QI-TA"],
["MI-TA", "MI-JA"],
["MI-TA", "RI-TA"],
["MI-TA", "MA-TA"],
["MI-TA", "I-TA"],
["MI-TA", "MI-TI"],
["MA-RI", "ME-RI"],
["MA-RI", "MA-RO"],
["MA-RI", "MA-RA"],
["MA-RI", "SA-RI"],
["MA-RI", "MA-DI"],
["MA-RI", "A-RI"],
["MA-RI", "MA-KI"],
["MA-RI", "-MA-RI"],
["QA-RE-TO", "QA-RE-JO"],
["MI-KA", "MI-KA-"],
["MI-KA", "MA-KA"],
["MI-KA", "MI-RA"],
["MI-KA", "RI-KA"],
["MI-KA", "MI-TA"],
["MI-KA", "MI-JA"],
["MI-KA", "DI-KA"],
["MI-KA", "I-KA"],
["MI-KA", "MI-KO"],
["MI-KA", "PI-KA"],
["TA-NE", "A-NE"],
["TA-NE", "KA-NE"],
["TA-NE", "TA-QE"],
["TA-NE", "TA-NO"],
["TA-NE", "QA-NE"],
["TA-NE", "TA-WE"],
["TA-NE", "MA-NE"],
["TA-NE", "TA-NA"],
["KA-RA2", "KA-RA-"],
["KA-RA2", "KA-RA"],
["KA-RA2", "QA-RA2"],
["KA-RA2", "KA-TA2"],
["KA-RA2", "KE-RA2"],
["KA-RA2", "TA-RA2"],
["A-RI", "A-RE"],
["A-RI", "A-RO"],
["A-RI", "MA-RI"],
["A-RI", "A-PI"],
["A-RI", "SA-RI"],
["A-RI", "A-KI"],
["A-RI", "A-TI"],
["A-RI", "-RI"],
["A-RI", "E-RI"],
["A-RI", "A-RA"],
["A-RI", "A-QI"],
["A-RI", "A-SI"],
["RU-DI", "RU-I"],
["RU-DI", "RU-KI"],
["RU-DI", "RU-SI"],
["RI-KA-TA", "MI-KA-TA"],
["RI-KA-TA", "RI-JA-TA"],
["RI-KA-TA", "RE-KA-TA"],
["RI-KA-TA", "RI-SA-TA"],
["NU-TE", "NU-SE"],
["NU-TE", "PU-TE"],
["NU-TE", "AU-TE"],
["NU-TE", "NU-WE"],
["NU-TE", "NU-TO"],
["NU-TE", "U-TE"],
["DA-KA", "KA-KA"],
["DA-KA", "MA-KA"],
["DA-KA", "PA-KA"],
["DA-KA", "QA-KA"],
["DA-KA", "A-KA"],
["DA-KA", "-DA-KA"],
["DA-KA", "RA-KA"],
["DA-KA", "DA-MA"],
["DA-KA", "NA-KA"],
["DA-KA", "DI-KA"],
["DA-KA", "DA-RA"],
["DA-KA", "DA-NA"],
["I-RA2", "-RA2"],
["I-RA2", "I-TA2"],
["I-RA2", "MI-RA2"],
["SI-KA", "RI-KA"],
["SI-KA", "MI-KA"],
["SI-KA", "SI-RA"],
["SI-KA", "SI-MA"],
["SI-KA", "DI-KA"],
["SI-KA", "I-KA"],
["SI-KA", "SI-JA"],
["SI-KA", "SI-QA"],
["SI-KA", "PI-KA"],
["SI-KA", "SI-ZA"],
["SI-TU", "SI-TO"],
["SI-TU", "TI-TU"],
["KA-SI", "PA-SI"],
["KA-SI", "KA-SI-"],
["KA-SI", "KA-SO"],
["KA-SI", "KA-WI"],
["KA-SI", "KI-SI"],
["KA-SI", "KA-NI"],
["KA-SI", "KU-SI"],
["KA-SI", "KA-TI"],
["KA-SI", "KA-SA"],
["KA-SI", "TA-SI"],
["KA-SI", "A-SI"],
["KA-RE-RO", "KA-TE-RO"],
["KA-RE-RO", "A-RE-RO"],
["TA-NI-KA", "TA-NI-KO"],
["RE-RO", "RE-WO"],
["RE-RO", "RU-RO"],
["RE-RO", "TE-RO"],
["RE-RO", "KE-RO"],
["RE-RO", "-E-RO"],
["RE-RO", "RE-TO"],
["RE-RO", "RE-MO"],
["RE-RO", "E-RO"],
["RE-RO", "DE-RO"],
["RE-RO", "ME-RO"],
["RE-RO", "QE-RO"],
["RE-RO", "PE-RO"],
["RE-RO", "ZE-RO"],
["RE-RO", "RI-RO"],
["RE-RO", "RE-O"],
["RE-RO", "WE-RO"],
["RE-RO", "RE-JO"],
["RE-RO", "RA-RO"],
["SI-PU", "SI-PU2"],
["A-JU", "A-DU"],
["A-JU", "A-PU"],
["A-JU", "A-NU"],
["A-JU", "A-JA"],
["TA-JA", "WA-JA"],
["TA-JA", "RA-JA"],
["TA-JA", "TI-JA"],
["TA-JA", "TA-ZA"],
["TA-JA", "PA-JA"],
["TA-JA", "TA-JO"],
["TA-JA", "TA-RA"],
["TA-JA", "KA-JA"],
["TA-JA", "TE-JA"],
["TA-JA", "A-JA"],
["TA-JA", "TA-NA"],
["SI-RU-TE", "PI-RU-TE"],
["DA-DA", "DI-DA"],
["DA-DA", "DA-MA"],
["DA-DA", "DA-RA"],
["DA-DA", "DA-NA"],
["JA-SA", "QA-SA"],
["JA-SA", "MA-SA"],
["JA-SA", "PA-SA"],
["JA-SA", "KA-SA"],
["JA-SA", "SA-SA"],
["JA-SA", "JA-SE"],
["JA-SA", "JA-SA-"],
["MA-I", "MA-"],
["MA-I", "MA-O"],
["MA-I", "MA-RI"],
["MA-I", "PA-I"],
["MA-I", "RA-I"],
["MA-I", "MA-DI"],
["MA-I", "MA-KI"],
["I-DI", "I-QI"],
["I-DI", "I-DU"],
["I-DI", "I-PI"],
["TU-NU", "TU-NI"],
["TU-NU", "TE-NU"],
["TU-NU", "RU-NU"],
["NU-RO", "PU-RO"],
["NU-RO", "NA-RO"],
["NU-RO", "RU-RO"],
["NU-RO", "NU-WO"],
["NU-RO", "DU-RO"],
["NU-RO", "TU-RO"],
["NU-RO", "NU-PO"],
["NU-RO", "NO-RO"],
["NU-RO", "NU-TO"],
["NU-RO", "AU-RO"],
["KA-SA", "KA-PA"],
["KA-SA", "KA-SI"],
["KA-SA", "KA-MA"],
["KA-SA", "KA-KA"],
["KA-SA", "KA-TA"],
["KA-SA", "KA-SO"],
["KA-SA", "QA-SA"],
["KA-SA", "KA-RA"],
["KA-SA", "MA-SA"],
["KA-SA", "KA-SA-"],
["KA-SA", "KA-NA"],
["KA-SA", "KA-ZA"],
["KA-SA", "KI-SA"],
["KA-SA", "PA-SA"],
["KA-SA", "SA-SA"],
["KA-SA", "KA-JA"],
["DI-SI", "DI-WI"],
["DI-SI", "KI-SI"],
["DI-SI", "DO-SI"],
["DI-SI", "DI-MI"],
["DI-SI", "DI-KI"],
["DI-SI", "DI-PI"],
["DI-SI", "DI-SO"],
["E-NA-SI", "E-NA-I"],
["TA-TA", "PA-TA"],
["TA-TA", "A-TA"],
["TA-TA", "KA-TA"],
["TA-TA", "TA-ZA"],
["TA-TA", "TA-TO"],
["TA-TA", "TA-RA"],
["TA-TA", "MA-TA"],
["TA-TA", "WA-TA"],
["TA-TA", "TE-TA"],
["TA-TA", "TA-NA"],
["KO-E", "KO-"],
["KO-E", "DO-E"],
["KO-E", "KE-E"],
["KO-E", "KO-U"],
["KO-E", "KO-WE"],
["KO-E", "ZO-E"],
["KO-E", "JO-E"],
["KO-E", "TO-E"],
["KO-E", "KO-A"],
["KO-E", "KO-TE"],
["I-SI", "-SI"],
["I-SI", "KI-SI"],
["I-SI", "I-SO"],
["I-SI", "I-QI"],
["I-SI", "A-SI"],
["I-SI", "I-PI"],
["I-PA-SA-JA", "I-KA-SA-JA"],
["A-MA-JA", "A-ME-JA"],
["A-MA-JA", "A-MI-JA"],
["A-TA", "A-MA"],
["A-TA", "-TA"],
["A-TA", "PA-TA"],
["A-TA", "KA-TA"],
["A-TA", "A-WA"],
["A-TA", "U-TA"],
["A-TA", "E-TA"],
["A-TA", "A-KA"],
["A-TA", "A2-TA"],
["A-TA", "A-TE"],
["A-TA", "A-TI"],
["A-TA", "MA-TA"],
["A-TA", "A-RA"],
["A-TA", "I-TA"],
["A-TA", "A-TA-"],
["A-TA", "WA-TA"],
["A-TA", "A-TO"],
["A-TA", "A-JA"],
["SI-NA", "I-NA"],
["SI-NA", "SI-RA"],
["SI-NA", "SI-MA"],
["SI-NA", "SI-JA"],
["SI-NA", "SI-QA"],
["SI-NA", "SI-ZA"],
["KA-TA-RE", "PA-TA-RE"],
["KA-TA-RE", "KA-PA-RE"],
["KA-TA-RE", "KA-TA-RO"],
["KA-TA-RE", "KA-TA-RA"],
["QA-NE", "QA-TE"],
["QA-NE", "A-NE"],
["QA-NE", "QA-NA"],
["QA-NE", "KA-NE"],
["QA-NE", "QA-NO"],
["QA-NE", "MA-NE"],
["TA-U", "TA-O"],
["TA-U", "TE-U"],
["TA-U", "TA-"],
["TA-U", "TA-SU"],
["MI-NA", "ME-NA"],
["MI-NA", "MI-RA"],
["MI-NA", "MI-KA"],
["MI-NA", "MI-TA"],
["MI-NA", "I-NA"],
["MI-NA", "MI-JA"],
["PA-TA", "A-TA"],
["PA-TA", "KA-TA"],
["PA-TA", "PI-TA"],
["PA-TA", "PA-KA"],
["PA-TA", "PA-TI"],
["PA-TA", "PA-JA"],
["PA-TA", "PA-NA"],
["PA-TA", "PA-TO"],
["PA-TA", "PU-TA"],
["PA-TA", "PA-TE"],
["PA-TA", "MA-TA"],
["PA-TA", "PE-TA"],
["PA-TA", "PA-SA"],
["PA-TA", "WA-TA"],
["PA-DA-NI", "PA-JA-NI"],
["PI-NU", "PI-RU"],
["PU-DE", "PA-DE"],
["PU-DE", "U-DE"],
["PU-DE", "PU-TE"],
["PU-DE", "PU-KE"],
["PU-DE", "PO-DE"],
["KU-NI-TE", "KU-NI-TA"],
["NA-KI", "PA-KI"],
["NA-KI", "NA-KA"],
["NA-KI", "A-KI"],
["NA-KI", "MA-KI"],
["NA-KI", "NI-KI"],
["NA-KI", "NA-NI"],
["NA-KI", "NA-KO"],
["NA-KI", "NA-PI"],
["QA-PU", "DA-PU"],
["QA-PU", "A-PU"],
["QA-PU", "MA-PU"],
["QA-PU", "PA-PU"],
["I-ZA", "I-NA"],
["I-ZA", "TI-ZA"],
["I-ZA", "I-KA"],
["I-ZA", "I-TA"],
["I-ZA", "I-JA"],
["I-ZA", "DI-ZA"],
["I-ZA", "-ZA"],
["I-ZA", "SI-ZA"],
["SE-I", "PE-I"],
["SE-I", "SE-"],
["SE-I", "SE-U"],
["SE-I", "RE-I"],
["SE-I", "TE-I"],
["KU-KA", "U-KA"],
["KU-KA", "RU-KA"],
["KU-KA", "KA-KA"],
["KU-KA", "KU-NA"],
["KU-KA", "KU-PA"],
["KU-KA", "NU-KA"],
["KU-KA", "PU-KA"],
["KU-KA", "KU-TA"],
["KU-KA", "-U-KA"],
["RU-NA", "RU-KA"],
["RU-NA", "KU-NA"],
["RU-NA", "RU-WA"],
["RU-NA", "PU-NA"],
["RU-NA", "RU-NU"],
["KA-JE", "KA-KE"],
["KA-JE", "KA-TE"],
["KA-JE", "KA-DE"],
["KA-JE", "KA-NE"],
["KA-JE", "WA-JE"],
["KA-JE", "KA-RE"],
["KA-JE", "KA-JA"],
["KA-JE", "KA-JO"],
["A-PA", "A-MA"],
["A-PA", "KA-PA"],
["A-PA", "O-PA"],
["A-PA", "A-TA"],
["A-PA", "A-PO"],
["A-PA", "A-WA"],
["A-PA", "A-PU"],
["A-PA", "A-KA"],
["A-PA", "SA-PA"],
["A-PA", "A-PI"],
["A-PA", "A-RA"],
["A-PA", "RA-PA"],
["A-PA", "A-JA"],
["A-PA", "A-PA-"],
["A-KA-TA", "-KA-TA"],
["A-KA-TA", "A-PA-TA"],
["A-KA-TA", "A-KA-TO"],
["A-KA-TA", "A-NA-TA"],
["A-KA-TA", "A-WA-TA"],
["A-KA-TA", "MA-KA-TA"],
["A-KA-TA", "A-KE-TA"],
["A-KA-TA", "WA-KA-TA"],
["SA-PU", "DA-PU"],
["SA-PU", "A-PU"],
["SA-PU", "MA-PU"],
["SA-PU", "SA-PA"],
["SA-PU", "SA-PI"],
["SA-PU", "SA-MU"],
["SA-PU", "PA-PU"],
["JA-SU", "RA-SU"],
["JA-SU", "JA-RU"],
["JA-SU", "JA-SE"],
["JA-SU", "TA-SU"],
["PU-RA", "PU-RO"],
["PU-RA", "PU-RI"],
["PU-RA", "PU-KA"],
["PU-RA", "PU-RU"],
["PU-RA", "PU-TA"],
["PU-RA", "-U-RA"],
["PU-RA", "PE-RA"],
["PU-RA", "PU-NA"],
["PU-RA", "U-RA"],
["PU-RA", "PU-WA"],
["PU-RA", "SU-RA"],
["QA-KI", "PA-KI"],
["QA-KI", "QA-KA"],
["QA-KI", "A-KI"],
["QA-KI", "MA-KI"],
["NU-SE", "NU-WE"],
["NU-SE", "SU-SE"],
["KA-I-KA", "RA-I-KA"],
["RU-JA", "RA-JA"],
["RU-JA", "RU-KA"],
["RU-JA", "RU-WA"],
["RU-JA", "RU-NA"],
["RU-JA", "RU-JO"],
["RU-JA", "RI-JA"],
["RU-JA", "RE-JA"],
["NI-PI", "PI-PI"],
["NI-PI", "NI-KI"],
["NI-PI", "DI-PI"],
["NI-PI", "I-PI"],
["NI-PI", "NA-PI"],
["JA-RA", "QA-RA"],
["JA-RA", "KA-RA"],
["JA-RA", "MA-RA"],
["JA-RA", "TA-RA"],
["JA-RA", "JA-RO"],
["JA-RA", "JA-RU"],
["JA-RA", "DA-RA"],
["JA-RA", "A-RA"],
["JA-RA", "JE-RA"],
["DA-WA", "DA-WO"],
["DA-WA", "A-WA"],
["DA-WA", "DA-MA"],
["DA-WA", "DA-NWA"],
["DA-WA", "RA-WA"],
["DA-WA", "DA-RA"],
["DA-WA", "DA-WI"],
["DA-WA", "DO-WA"],
["DA-WA", "DA-NA"],
["DA-WA", "DA-WE"],
["I-JA", "NI-JA"],
["I-JA", "QI-JA"],
["I-JA", "-JA"],
["I-JA", "KI-JA"],
["I-JA", "-I-JA"],
["I-JA", "PI-JA"],
["I-JA", "I-JO"],
["I-JA", "TI-JA"],
["I-JA", "I-NA"],
["I-JA", "MI-JA"],
["I-JA", "I-JE"],
["I-JA", "RI-JA"],
["I-JA", "WI-JA"],
["I-JA", "I-KA"],
["I-JA", "SI-JA"],
["I-JA", "I-TA"],
["I-JA", "A-JA"],
["JA-QE", "JO-QE"],
["JA-QE", "TA-QE"],
["JA-QE", "JA-SE"],
["JA-QE", "JA-QO"],
["JA-QE", "JA-DE"],
["JA-QE", "MA-QE"],
["JA-WA", "A-WA"],
["JA-WA", "JE-WA"],
["JA-WA", "RA-WA"],
["JA-WA", "JA-WO"],
["JA-SI", "PA-SI"],
["JA-SI", "KA-SI"],
["JA-SI", "JA-PI"],
["JA-SI", "JA-SE"],
["JA-SI", "JO-SI"],
["JA-SI", "TA-SI"],
["JA-SI", "A-SI"],
["JA-SI", "JA-TI"],
["WI-PI", "WO-PI"],
["WI-PI", "PI-PI"],
["WI-PI", "NI-PI"],
["WI-PI", "DI-PI"],
["WI-PI", "I-PI"],
["A-PI", "O-PI"],
["A-PI", "A-PO"],
["A-PI", "E-PI"],
["A-PI", "A-PU"],
["A-PI", "-PI"],
["A-PI", "SA-PI"],
["A-PI", "A-PI-"],
["A-PI", "A-KI"],
["A-PI", "A-TI"],
["A-PI", "A-RI"],
["A-PI", "JA-PI"],
["A-PI", "A-QI"],
["A-PI", "A-SI"],
["A-PI", "I-PI"],
["A-PI", "NA-PI"],
["I-WA-JA", "I-TA-JA"],
["I-WA-JA", "I-WA-KA"],
["I-WA-JA", "-WA-JA"],
["O-DA", "O-NA"],
["O-DA", "O-KA"],
["O-DA", "O-MA"],
["O-DA", "O-PA"],
["O-DA", "O-DA-"],
["O-DA", "-DA"],
["O-DA", "O-DU"],
["O-DA", "NO-DA"],
["O-DA", "O-RA"],
["O-DA", "PO-DA"],
["O-DA", "O-QA"],
["O-DA", "MO-DA"],
["A-WA-PI", "A-WA-SI"],
["A-WA-PI", "A-SA-PI"],
["A-DA-RA", "SA-DA-RA"],
["A-DA-RA", "A-TA-RA"],
["JA-SA-JA", "PA-SA-JA"],
["TU-RU-SA", "TE-RU-SA"],
["A-MA", "O-MA"],
["A-MA", "KA-MA"],
["A-MA", "A-TA"],
["A-MA", "U-MA"],
["A-MA", "A-WA"],
["A-MA", "A-ME"],
["A-MA", "A-KA"],
["A-MA", "SA-MA"],
["A-MA", "DA-MA"],
["A-MA", "A-MO"],
["A-MA", "A-RA"],
["A-MA", "-MA"],
["A-MA", "A-JA"],
["DU-RA", "DE-RA"],
["DU-RA", "DU-RI"],
["DU-RA", "DU-MA"],
["DU-RA", "PU-RA"],
["DU-RA", "DA-RA"],
["DU-RA", "-U-RA"],
["DU-RA", "DU-RO"],
["DU-RA", "U-RA"],
["DU-RA", "DU-RU"],
["DU-RA", "SU-RA"],
["DU-RA", "DI-RA"],
["RE-TI", "RE-TO"],
["RE-TI", "RE-I"],
["RE-TI", "RE-TA"],
["RE-TI", "RE-TE"],
["RE-TI", "RE-SI"],
["RE-TI", "RI-TI"],
["RE-TI", "ME-TI"],
["JA-KU", "RA-KU"],
["JA-KU", "JA-RU"],
["JA-KU", "MA-KU"],
["JA-KU", "JA-KO"],
["A-JA", "A-MA"],
["A-JA", "WA-JA"],
["A-JA", "-JA"],
["A-JA", "A-JA-"],
["A-JA", "RA-JA"],
["A-JA", "A-TA"],
["A-JA", "A-WA"],
["A-JA", "A-KA"],
["A-JA", "PA-JA"],
["A-JA", "A-RA"],
["A-JA", "I-JA"],
["A-JA", "KA-JA"],
["DU-KA", "U-KA"],
["DU-KA", "RU-KA"],
["DU-KA", "NU-KA"],
["DU-KA", "PU-KA"],
["DU-KA", "KU-KA"],
["DU-KA", "DU-MA"],
["DU-KA", "DI-KA"],
["DU-KA", "-U-KA"],
["KI-RU", "KU-RU"],
["KI-RU", "I-RU"],
["KI-RU", "PI-RU"],
["KI-RU", "KI-RI"],
["KI-RU", "KO-RU"],
["KI-RU", "KI-RO"],
["I-DA", "DI-DA"],
["I-DA", "I-NA"],
["I-DA", "-DA"],
["I-DA", "I-KA"],
["I-DA", "I-TA"],
["I-DA", "I-JA"],
["I-DA", "I-DU"],
["KU-PA-RI", "KU-PA-RO"],
["KU-PA-RI", "KU-PI-RI"],
["E-KA", "E-KE"],
["E-KA", "O-KA"],
["E-KA", "E-RA"],
["E-KA", "U-KA"],
["E-KA", "E-KI"],
["E-KA", "E-KO"],
["E-KA", "-KA"],
["E-KA", "E-TA"],
["E-KA", "A-KA"],
["E-KA", "RE-KA"],
["E-KA", "I-KA"],
["E-KA", "E-WA"],
["E-KA", "E-NA"],
["E-KA", "E-QA"],
["A-RI-PA", "A-RO-PA"],
["A-RI-PA", "A-RI-QA"],
["TO-ME", "TO-MO"],
["TO-ME", "PO-ME"],
["TO-ME", "TO-DE"],
["TO-ME", "TO-TE"],
["TO-ME", "O-ME"],
["TO-ME", "TO-E"],
["TO-ME", "TO-MA"],
["TO-ME", "TO-RE"],
["A-NU", "O-NU"],
["A-NU", "A-DU"],
["A-NU", "A-NE"],
["A-NU", "A-PU"],
["A-NU", "-NU"],
["A-NU", "RA-NU"],
["A-NU", "A-NU-"],
["A-NU", "A-NO"],
["I-NA", "O-NA"],
["I-NA", "-NA"],
["I-NA", "I-NO"],
["I-NA", "I-KA"],
["I-NA", "I-TA"],
["I-NA", "I-JA"],
["I-NA", "E-NA"],
["DI-PA-JA", "DI-PI-JA"],
["DA-RA", "DE-RA"],
["DA-RA", "QA-RA"],
["DA-RA", "DA-RO"],
["DA-RA", "KA-RA"],
["DA-RA", "MA-RA"],
["DA-RA", "DA-MA"],
["DA-RA", "TA-RA"],
["DA-RA", "A-RA"],
["DA-RA", "DA-NA"],
["DA-RA", "DI-RA"],
["A-MI", "A3-MI"],
["A-MI", "A-MA"],
["A-MI", "A-MI-"],
["A-MI", "A-ME"],
["A-MI", "A-PI"],
["A-MI", "-MI"],
["A-MI", "A-MO"],
["A-MI", "A-KI"],
["A-MI", "DA-MI"],
["A-MI", "A-TI"],
["A-MI", "A-RI"],
["A-MI", "E-MI"],
["A-MI", "A-QI"],
["A-MI", "A-SI"],
["A-MI", "SA-MI"],
["MA-TE-RE", "MA-TE-DE"],
["MA-TE-RE", "TA-TE-RE"],
["MA-TE-RE", "MA-TE-WE"],
["TI-NA", "TI-NO"],
["TI-NA", "TI-RA"],
["TI-NA", "TO-NA"],
["TI-NA", "TI-JA"],
["TI-NA", "TI-MA"],
["TI-NA", "I-NA"],
["TI-NA", "TI-ZA"],
["TI-NA", "TA-NA"],
["WI-JA", "WA-JA"],
["WI-JA", "NI-JA"],
["WI-JA", "QI-JA"],
["WI-JA", "KI-JA"],
["WI-JA", "-I-JA"],
["WI-JA", "PI-JA"],
["WI-JA", "TI-JA"],
["WI-JA", "WI-SA"],
["WI-JA", "MI-JA"],
["WI-JA", "WE-JA"],
["WI-JA", "WI-JO"],
["WI-JA", "RI-JA"],
["WI-JA", "-WI-JA"],
["WI-JA", "SI-JA"],
["WI-JA", "I-JA"],
["PI-O", "PI-KO"],
["PI-O", "PI-"],
["PI-O", "PI-RO"],
["PI-O", "PE-O"],
["RO-E", "RO-A"],
["RO-E", "DO-E"],
["RO-E", "RO-"],
["RO-E", "ZO-E"],
["RO-E", "RO-WE"],
["RO-E", "JO-E"],
["RO-E", "TO-E"],
["A-PA3", "A-PA-"],
["A-RI-JA", "A-NI-JA"],
["A-RI-JA", "I-RI-JA"],
["A-RI-JA", "A-RE-JA"],
["A-RI-JA", "-RI-JA"],
["A-RI-JA", "A-RO-JA"],
["A-RI-JA", "A-RI-QA"],
["A-RI-JA", "A-MI-JA"],
["PA-TA-DA", "PA-TA-JA"],
["DU-RI", "PU-RI"],
["DU-RI", "TU-RI"],
["DU-RI", "SU-RI"],
["DU-RI", "DU-NI"],
["DU-RI", "DO-RI"],
["DU-RI", "DU-RO"],
["DU-RI", "DU-RU"],
["SU-KI-RI-TA", "SU-KI-RI-TO"],
["JA-DI", "MA-DI"],
["JA-DI", "JA-PI"],
["JA-DI", "JA-DE"],
["JA-DI", "JA-TI"],
["JA-DI", "JA-DO"],
["TI-TI-MA", "TI-TA-MA"],
["SI-MA", "SI-MO"],
["SI-MA", "PI-MA"],
["SI-MA", "SA-MA"],
["SI-MA", "TI-MA"],
["SI-MA", "SI-RA"],
["SI-MA", "SI-JA"],
["SI-MA", "SI-QA"],
["SI-MA", "RI-MA"],
["SI-MA", "SI-ZA"],
["I-JA-TE", "I-JO-TE"],
["NE-TI", "NE-TO"],
["NE-TI", "ME-TI"],
["NE-TI", "NE-WI"],
["KA-QA", "KA-PA"],
["KA-QA", "KA-MA"],
["KA-QA", "KA-KA"],
["KA-QA", "KA-TA"],
["KA-QA", "KA-RA"],
["KA-QA", "KA-NA"],
["KA-QA", "KA-ZA"],
["KA-QA", "KA-SA"],
["KA-QA", "SA-QA"],
["KA-QA", "KA-JA"],
["O-TE-JA", "E-TE-JA"],
["O-TE-JA", "TO-TE-JA"],
["O-TE-JA", "O-TE-RA"],
["NI-MI", "NI-MO"],
["NI-MI", "DI-MI"],
["NI-MI", "NI-PI"],
["NI-MI", "NI-KI"],
["TU-SU", "KU-SU"],
["TU-SU", "U-SU"],
["TU-SU", "TA-SU"],
["TU-ME-I", "TU-MA-I"],
["I-PI", "O-PI"],
["I-PI", "E-PI"],
["I-PI", "-PI"],
["I-PI", "A-PI"],
["I-PI", "PI-PI"],
["I-PI", "I-QI"],
["I-PI", "NI-PI"],
["I-PI", "DI-PI"],
["RA-ME", "NA-ME"],
["RA-ME", "SA-ME"],
["RA-ME", "A-ME"],
["RA-ME", "RA-DE"],
["RA-ME", "RA-ZE"],
["RA-ME", "RA-KE"],
["RA-ME", "RA-MO"],
["TU-ME", "TO-ME"],
["TU-ME", "TU-MA"],
["TO-SA", "TO-QA"],
["TO-SA", "TO-SO"],
["TO-SA", "TO-WA"],
["TO-SA", "TO-NA"],
["TO-SA", "TO-SA-"],
["TO-SA", "TO-RA"],
["TO-SA", "TO-PA"],
["TO-SA", "TO-MA"],
["RE-JA", "NE-JA"],
["RE-JA", "RA-JA"],
["RE-JA", "RE-WA"],
["RE-JA", "RE-ZA"],
["RE-JA", "RE-TA"],
["RE-JA", "RE-KA"],
["RE-JA", "WE-JA"],
["RE-JA", "RI-JA"],
["RE-JA", "ME-JA"],
["RE-JA", "TE-JA"],
["RE-JA", "RE-JO"],
["RE-JA", "KE-JA"],
["RE-JA", "RE-A"],
["JA-JA", "WA-JA"],
["JA-JA", "RA-JA"],
["JA-JA", "PA-JA"],
["JA-JA", "KA-JA"],
["JA-JA", "A-JA"],
["U-NA-KA", "A-NA-KA"],
["SE-TO-I-JA", "SE-TO-I-JO"],
["TE-JA", "NE-JA"],
["TE-JA", "TE-PA"],
["TE-JA", "TE-RA"],
["TE-JA", "TI-JA"],
["TE-JA", "TE-JO"],
["TE-JA", "WE-JA"],
["TE-JA", "TE-WA"],
["TE-JA", "RE-JA"],
["TE-JA", "TE-JE"],
["TE-JA", "ME-JA"],
["TE-JA", "KE-JA"],
["TE-JA", "TE-TA"],
["DA-KU", "DA-PU"],
["DA-KU", "RA-KU"],
["DA-KU", "MA-KU"],
["MI-JA", "NI-JA"],
["MI-JA", "QI-JA"],
["MI-JA", "KI-JA"],
["MI-JA", "-I-JA"],
["MI-JA", "MI-RA"],
["MI-JA", "MI-KA"],
["MI-JA", "PI-JA"],
["MI-JA", "TI-JA"],
["MI-JA", "MI-TA"],
["MI-JA", "RI-JA"],
["MI-JA", "WI-JA"],
["MI-JA", "MI-JO"],
["MI-JA", "SI-JA"],
["MI-JA", "I-JA"],
["MI-JA", "ME-JA"],
["RO-QA", "TO-QA"],
["RO-QA", "RO-A"],
["RO-QA", "RO-ZA"],
["RO-QA", "RO-KA"],
["RO-QA", "-RO-QA"],
["RO-QA", "PO-QA"],
["RO-QA", "O-QA"],
["WA-TE", "WA-TU"],
["WA-TE", "QA-TE"],
["WA-TE", "WA-TO"],
["WA-TE", "KA-TE"],
["WA-TE", "WA-TE-"],
["WA-TE", "A-TE"],
["WA-TE", "PA-TE"],
["WA-TE", "MA-TE"],
["WA-TE", "WA-JE"],
["WA-TE", "WA-TA"],
["WA-TE", "WA-DE"],
["A-NE", "O-NE"],
["A-NE", "A-E"],
["A-NE", "A-RE"],
["A-NE", "A-ME"],
["A-NE", "A-NU"],
["A-NE", "-NE"],
["A-NE", "A-WE"],
["A-NE", "KA-NE"],
["A-NE", "A-KE"],
["A-NE", "A-TE"],
["A-NE", "A-SE"],
["A-NE", "U-NE"],
["A-NE", "QA-NE"],
["A-NE", "A-NO"],
["A-NE", "MA-NE"],
["A-RE", "A-E"],
["A-RE", "A-ME"],
["A-RE", "A-NE"],
["A-RE", "A-RO"],
["A-RE", "U-RE"],
["A-RE", "PA-RE"],
["A-RE", "A-WE"],
["A-RE", "A-KE"],
["A-RE", "A-TE"],
["A-RE", "A-RE-"],
["A-RE", "E-RE"],
["A-RE", "-RE"],
["A-RE", "A-RI"],
["A-RE", "A-SE"],
["A-RE", "A-RA"],
["A-RE", "KA-RE"],
["A-RE", "O-RE"],
["A-JE", "A-E"],
["A-JE", "A-RE"],
["A-JE", "-JE"],
["A-JE", "A-ME"],
["A-JE", "A-NE"],
["A-JE", "A-WE"],
["A-JE", "A-KE"],
["A-JE", "A-TE"],
["A-JE", "I-JE"],
["A-JE", "A-SE"],
["A-JE", "WA-JE"],
["A-JE", "A-JA"],
["NE-MI", "TE-MI"],
["NE-MI", "E-MI"],
["NE-MI", "NE-WI"],
["MI-NE", "MA-NE"],
["NE-KI", "E-KI"],
["NE-KI", "KE-KI"],
["NE-KI", "NI-KI"],
["NE-KI", "NE-KI-"],
["NE-KI", "NE-WI"],
["A-DA", "A-MA"],
["A-DA", "A-TA"],
["A-DA", "A-DU"],
["A-DA", "A-WA"],
["A-DA", "A-KA"],
["A-DA", "-DA"],
["A-DA", "A-RA"],
["A-DA", "A-JA"],
["KI-RI-SI", "TI-RI-SI"],
["KI-RE-ZA", "KE-RE-ZA"],
["E-MI", "E-NI"],
["E-MI", "TE-MI"],
["E-MI", "E-KI"],
["E-MI", "E-PI"],
["E-MI", "-MI"],
["E-MI", "E-RI"],
["E-MI", "E-ME"],
["A-TI-RU", "A-TI-RO"],
["A-TI-RU", "A-QI-RU"],
["JA-PA", "KA-PA"],
["JA-PA", "SA-PA"],
["JA-PA", "JA-PI"],
["JA-PA", "RA-PA"],
["JA-PA", "JA-PO"],
["E-*82", "-*82"],
["KA-DI", "KA-SI"],
["KA-DI", "KA-WI"],
["KA-DI", "KA-DE"],
["KA-DI", "KA-NI"],
["KA-DI", "KA-TI"],
["KA-DI", "MA-DI"],
["I-SE", "-SE"],
["I-SE", "E-SE"],
["I-SE", "I-SO"],
["I-SE", "I-QE"],
["I-SE", "I-WE"],
["I-SE", "TI-SE"],
["I-SE", "I-JE"],
["I-SE", "A-SE"],
["PA-ZA", "PA-TA"],
["PA-ZA", "PA-KA"],
["PA-ZA", "TA-ZA"],
["PA-ZA", "PA-JA"],
["PA-ZA", "PA-NA"],
["PA-ZA", "KA-ZA"],
["PA-ZA", "PA-SA"],
["PA-ZA", "PE-ZA"],
["PA-ZA", "PA-ZE"],
["I-MA", "A-MA"],
["I-MA", "O-MA"],
["I-MA", "PI-MA"],
["I-MA", "U-MA"],
["I-MA", "TI-MA"],
["I-MA", "I-NA"],
["I-MA", "SI-MA"],
["I-MA", "I-KA"],
["I-MA", "I-TA"],
["I-MA", "I-JA"],
["I-MA", "-MA"],
["I-MA", "RI-MA"],
["U-JU", "U-JO"],
["U-JU", "U-SU"],
["A-RA-TU", "A-RA-RU"],
["A-TA-RE", "PA-TA-RE"],
["A-TA-RE", "A-TA-QE"],
["A-TA-RE", "A-TA-RA"],
["A-TA-RE", "A-TA-RO"],
["KA-I-RO", "KO-I-RO"],
["RO-SI-RA", "RO-SI-JA"],
["A-TA-NA", "A-TA-NO"],
["A-TA-NA", "A-TA-RA"],
["MA-JU", "MA-JO"],
["MA-JU", "MA-PU"],
["MA-JU", "MA-KU"],
["TA-NA-TE", "TA-NA-TO"],
["TA-NA-TE", "TA-NA-TI"],
["MA-ZA", "MA-KA"],
["MA-ZA", "MA-SA"],
["MA-ZA", "TA-ZA"],
["MA-ZA", "MA-RA"],
["MA-ZA", "KA-ZA"],
["MA-ZA", "MA-TA"],
["A-DE", "PA-DE"],
["A-DE", "A-E"],
["A-DE", "-DE"],
["A-DE", "A-RE"],
["A-DE", "A-DU"],
["A-DE", "U-DE"],
["A-DE", "A-ME"],
["A-DE", "RA-DE"],
["A-DE", "A-NE"],
["A-DE", "KA-DE"],
["A-DE", "SA-DE"],
["A-DE", "A-WE"],
["A-DE", "A-KE"],
["A-DE", "A-TE"],
["A-DE", "A-SE"],
["A-DE", "JA-DE"],
["A-DE", "E-DE"],
["A-DE", "WA-DE"],
["A-MI-TA", "A-MO-TA"],
["A-MI-TA", "A-TI-TA"],
["A-MI-TA", "A-MI-JA"],
["A-MI-TA", "A-QI-TA"],
["E-TO-RI", "KE-TO-RI"],
["I-DE", "-DE"],
["I-DE", "U-DE"],
["I-DE", "I-QE"],
["I-DE", "I-WE"],
["I-DE", "I-JE"],
["I-DE", "KI-DE"],
["I-DE", "DI-DE"],
["I-DE", "I-DU"],
["I-DE", "E-DE"],
["SU-PA", "SU-PO"],
["SU-PA", "SU-ZA"],
["SU-PA", "KU-PA"],
["SU-PA", "SA-PA"],
["SU-PA", "SU-RA"],
["ME-KI-DI", "ME-KI-TI"],
["QA-TI-JU", "QA-TI-JA"],
["KU-PI", "KU-PA"],
["KU-PI", "KU-SI"],
["KU-PI", "KO-PI"],
["KU-PI", "KU-PO"],
["JA-WI", "KA-WI"],
["JA-WI", "RA-WI"],
["JA-WI", "JA-PI"],
["JA-WI", "DA-WI"],
["JA-WI", "JA-WO"],
["JA-WI", "JA-TI"],
["JA-WI", "WA-WI"],
["RA-TE", "QA-TE"],
["RA-TE", "RA-PTE"],
["RA-TE", "RA-TO"],
["RA-TE", "KA-TE"],
["RA-TE", "RA-DE"],
["RA-TE", "RA-ZE"],
["RA-TE", "RE-TE"],
["RA-TE", "RA-KE"],
["RA-TE", "WA-TE"],
["RA-TE", "A-TE"],
["RA-TE", "PA-TE"],
["RA-TE", "MA-TE"],
["RA-TE", "RA-TU"],
["KU-RA", "KU-RU"],
["KU-RA", "KU-NA"],
["KU-RA", "KA-RA"],
["KU-RA", "KU-PA"],
["KU-RA", "KE-RA"],
["KU-RA", "KU-KA"],
["KU-RA", "KO-RA"],
["KU-RA", "PU-RA"],
["KU-RA", "-U-RA"],
["KU-RA", "KU-TA"],
["KU-RA", "U-RA"],
["KU-RA", "KU-RE"],
["KU-RA", "SU-RA"],
["PI-MU", "PI-MA"],
["PI-MU", "PI-RU"],
["TA-KE", "KA-KE"],
["TA-KE", "TE-KE"],
["TA-KE", "RA-KE"],
["TA-KE", "A-KE"],
["TA-KE", "TA-QE"],
["TA-KE", "TA-WE"],
["SA-RI", "SU-RI"],
["SA-RI", "MA-RI"],
["SA-RI", "SA-PI"],
["SA-RI", "A-RI"],
["SA-RI", "SA-MI"],
["DU-JU", "DU-RU"],
["TE-TE", "TE-RE"],
["TE-TE", "-TE-TE"],
["TE-TE", "TE-KE"],
["TE-TE", "RE-TE"],
["TE-TE", "TE-WE"],
["TE-TE", "E-TE"],
["TE-TE", "QE-TE"],
["TE-TE", "TO-TE"],
["TE-TE", "ME-TE"],
["TE-TE", "TE-JE"],
["TE-TE", "TWE-TE"],
["TE-TE", "TE-TO"],
["TE-TE", "TE-PE"],
["TE-TE", "TE-TA"],
["MI-RE", "MI-RA"],
["MI-RE", "MO-RE"],
["SI-TE", "SI-TO"],
["SI-TE", "SI-WE"],
["SI-TE", "KI-TE"],
["DI-DI", "DI-WI"],
["DI-DI", "DI-DA"],
["DI-DI", "DI-MI"],
["DI-DI", "DI-KI"],
["DI-DI", "DI-DE"],
["DI-DI", "DI-PI"],
["JA-KI", "PA-KI"],
["JA-KI", "A-KI"],
["JA-KI", "JA-PI"],
["JA-KI", "MA-KI"],
["JA-KI", "JA-KO"],
["JA-KI", "JA-TI"],
["DI-KI", "DI-WI"],
["DI-KI", "DI-MI"],
["DI-KI", "DI-KA"],
["DI-KI", "NI-KI"],
["DI-KI", "DI-PI"],
["O-MI", "O-MA"],
["O-MI", "O-PI"],
["O-MI", "-MI"],
["O-MI", "O-ME"],
["O-MI", "E-MI"],
["O-MI", "O-MO"],
["O-MI", "O-KI"],
["PU2-RE-JA", "PU2-RE-WA"],
["KO-MU", "KO-U"],
["KO-MU", "KO-MA"],
["KO-MU", "KO-DU"],
["KO-MU", "KO-RU"],
["KO-MU", "KO-TU"],
["KO-MU", "KO-KU"],
["KO-MU", "KO-PU"],
["NA-SI", "PA-SI"],
["NA-SI", "KA-SI"],
["NA-SI", "NA-SO"],
["NA-SI", "NA-NI"],
["NA-SI", "TA-SI"],
["NA-SI", "A-SI"],
["NA-SI", "NA-PI"],
["TA-PI", "A-PI"],
["TA-PI", "SA-PI"],
["TA-PI", "JA-PI"],
["TA-PI", "TA-SI"],
["TA-PI", "NA-PI"],
["JA-RE", "A-RE"],
["JA-RE", "PA-RE"],
["JA-RE", "JA-RO"],
["JA-RE", "JA-RU"],
["JA-RE", "KA-RE"],
["JA-RE", "JA-SE"],
["JA-RE", "JA-DE"],
["RU-MI", "RU-I"],
["RU-MI", "RU-KI"],
["RU-MI", "RU-SI"],
["RU-MI", "SU-MI"],
["KA-NE", "KA-KE"],
["KA-NE", "KA-NO"],
["KA-NE", "KU-NE"],
["KA-NE", "KA-TE"],
["KA-NE", "KE-NE"],
["KA-NE", "A-NE"],
["KA-NE", "KA-DE"],
["KA-NE", "KA-NI"],
["KA-NE", "KA-NA"],
["KA-NE", "KA-RE"],
["KA-NE", "QA-NE"],
["KA-NE", "MA-NE"],
["KI-NU", "KE-NU"],
["JA-PI", "A-PI"],
["JA-PI", "SA-PI"],
["JA-PI", "JA-TI"],
["JA-PI", "JA-PO"],
["JA-PI", "NA-PI"],
["NI-TA", "NI-JA"],
["NI-TA", "PI-TA"],
["NI-TA", "MI-TA"],
["NI-TA", "QI-TA"],
["NI-TA", "NI-TO"],
["NI-TA", "RI-TA"],
["NI-TA", "I-TA"],
["DE-SU", "DE-SO"],
["DE-SU", "DE-U"],
["*47-TE", "*47-DE"],
["DE-MI", "TE-MI"],
["DE-MI", "DI-MI"],
["DE-MI", "DA-MI"],
["DE-MI", "E-MI"],
["I-*47", "A-*47"],
["A-KI-RO", "A-KO-RO"],
["A-KI-RO", "-KI-RO"],
["A-KI-RO", "O-KI-RO"],
["A-KI-RO", "A-KE-RO"],
["A-KI-RO", "A-KU-RO"],
["A-KI-RO", "A-TI-RO"],
["A-KI-RO", "A-KI-TO"],
["A-KI-RO", "A-QI-RO"],
["A-KI-RO", "A-KI-RI"],
["A-DA-RO", "QA-DA-RO"],
["A-DA-RO", "A-QA-RO"],
["A-DA-RO", "A-TA-RO"],
["A-DA-RO", "A-SA-RO"],
["A-DA-RO", "KA-DA-RO"],
["TA-MA", "A-MA"],
["TA-MA", "KA-MA"],
["TA-MA", "TA-ZA"],
["TA-MA", "SA-MA"],
["TA-MA", "TI-MA"],
["TA-MA", "DA-MA"],
["TA-MA", "TA-RA"],
["TA-MA", "TO-MA"],
["TA-MA", "TU-MA"],
["TA-MA", "TA-NA"],
["A-TA-DE", "A-TA-QE"],
["A-TA-DE", "A-KA-DE"],
["A-RO-TE", "A-RO-TA"],
["A-RO-TE", "A-RO-WE"],
["A-RO-TE", "A-PO-TE"],
["A-RO-TE", "A-MO-TE"],
["SI-DA-RO", "SI-TA-RO"],
["SI-DA-RO", "SI-DA-JO"],
["SI-DA-RO", "KI-DA-RO"],
["SI-DA-RO", "SI-RA-RO"],
["SE-SI", "RE-SI"],
["SE-SI", "ME-SI"],
]);
