var commodities = new Map([
['𐘏', 'sheep'],
['𐘐', 'ewe'],
['𐘑', 'ram'],
['𐘒', 'goat'],
['𐘓', 'she-goat'],
['𐘔', 'he-goat'],
['𐘕', 'ox'],
['𐘕', 'bovine'],
['𐘖', 'bull'],
['𐘝', 'figs'],
['𐘞', 'sesame'],
['𐘞', 'flax'],
['𐘮', 'cloth'],
['𐘶', 'flour'],
['𐙄', 'pig'],
['𐙉', 'grain'],
['𐙉', 'wheat'],
['𐙊', 'grain'],
['𐙋', 'olives'],
['𐙋', 'olives'],
['𐙌', 'spice'],
['𐙍', 'wine'],
['𐙎', 'lesser quality wine'],
['𐙏', 'vinegar'],
['𐙐', 'textile?'],
['𐙑', 'fodder?'],
['𐙒', 'hide?'],
['𐙔', 'helmet'],
['𐙖', 'olive oil'],
['𐙗', 'cyperus'],
['𐙘', 'coriander?'],
['𐙾', 'boots?'],
['𐙉', 'grain'],
['𐛟', 'grain'],
['𐛬', 'grain'],
['𐛭', 'grain'],
['𐛮', 'grain'],
['𐛯', 'grain'],
['𐛱', 'grain'],
['𐛲', 'grain'],
['𐛵', 'grain'],
['𐛷', 'grain'],
['𐛳', 'grain'],
['𐙗', 'cyperus'],
['𐜙', 'cyperus'],
['𐜙', 'cyperus'],
['𐜚', 'cyperus'],
['𐜚', 'cyperus'],
['𐜛', 'cyperus'],
['𐙖', 'olive oil'],
['𐙜', 'olive oil'],
['𐙘', 'olive oil'],
['𐜉', 'olive oil'],
['𐜉', 'olive oil'],
['𐜊', 'olive oil'],
['𐜋', 'olive oil'],
['𐜋', 'olive oil'],
['𐜌', 'olive oil'],
['𐜍', 'olive oil'],
['𐜍', 'olive oil'],
['𐜎', 'olive oil'],
['𐜎', 'olive oil'],
['𐜏', 'olive oil'],
['𐜏', 'olive oil'],
['𐜐', 'olive oil'],
['𐜐', 'olive oil'],
['𐜑', 'olive oil'],
['𐜒', 'olive oil'],
['𐜓', 'olive oil'],
['𐜓', 'olive oil'],
['𐜔', 'olive oil'],
['𐜕', 'olive oil'],
['𐜖', 'olive oil'],
['𐜗', 'olive oil'],
['𐜘', 'olive oil'],
['𐙍', 'wine'],
['𐛾', 'wine'],
['𐙍', 'wine'],
['𐛽', 'wine'],
['𐙍', 'wine'],
['𐘞𐙍', 'wine'],
['𐛼', 'wine'],
['𐜀', 'wine'],
['𐜂', 'wine'],
['𐛻', 'wine'],
['𐛿', 'wine'],
['𐜁', 'wine'],
['𐘋𐙍', 'wine'],
['𐙍𐘻', 'wine'],
['𐘻', 'liquid?'],
['𐛚', 'liquid?'],
['𐛜', 'liquid?'],
['𐛜', 'liquid?'],
['𐛛', 'liquid?'],
['𐛙', 'liquid?'],
['𐛝', 'liquid?'],
['𐚻', 'liquid?'],
['𐚹', 'liquid?'],
['𐚻', 'liquid?'],
['𐚼', 'liquid?'],
['𐚹', 'liquid?'],
['𐚺', 'liquid?'],
['𐚻', 'liquid?'],
['𐚹', 'liquid?'],
['𐚻', 'liquid?'],
['𐙈"', 'bronze'],
['𐙇', 'men'],
['𐛧', 'men'],
['𐛨', 'men'],
['𐛩', 'men'],
['𐛪', 'men'],
['𐛫', 'men'],
['𐜉', 'oil'],
['𐜊', 'oil'],
['𐜋', 'oil'],
['𐜌', 'oil'],
['𐜍', 'oil'],
['𐜎', 'oil'],
['𐜏', 'oil'],
['𐜐', 'oil'],
['𐜑', 'oil'],
['𐜒', 'oil'],
['𐜓', 'oil'],
['𐜔', 'oil'],
['𐜕', 'oil'],
['𐜖', 'oil'],
['𐜗', 'oil'],
['𐜘', 'oil'],
['𐛺', 'olives'],
]);


